(function(){function j(a){throw a;}var l=void 0,m=!0,q=null,r=!1;function ba(){return function(){}}function ca(a){return function(){return this[a]}}function da(a){return function(){return a}}var s,u=this;function fa(a){a=a.split(".");for(var b=u,c;c=a.shift();)if(b[c]!=q)b=b[c];else return q;return b}
function ga(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function v(a){return a!==l}function w(a){return"array"==ga(a)}function ha(a){var b=ga(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"string"==typeof a}function ia(a){return"boolean"==typeof a}function y(a){return"number"==typeof a}function ja(a){return"function"==ga(a)}function z(a){var b=typeof a;return"object"==b&&a!=q||"function"==b}function ka(a){return a[ma]||(a[ma]=++na)}
var ma="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),na=0;function oa(a,b,c){return a.call.apply(a.bind,arguments)}function pa(a,b,c){a||j(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}
function qa(a,b,c){qa=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?oa:pa;return qa.apply(q,arguments)}var ra=Date.now||function(){return+new Date};function sa(a,b){var c=a.split("."),d=u;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&v(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function A(a,b){function c(){}c.prototype=b.prototype;a.xa=b.prototype;a.prototype=new c};function ta(a){if(!ua.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(va,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(wa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(xa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ya,"&quot;"));return a}var va=/&/g,wa=/</g,xa=/>/g,ya=/\"/g,ua=/[&<>\"]/,za={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},Aa={"'":"\\'"};
function C(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=b,g=c+1,h;if(!(h=za[d])){if(!(31<e&&127>e))if(d in Aa)d=Aa[d];else if(d in za)d=Aa[d]=za[d];else{e=d;h=d.charCodeAt(0);if(31<h&&127>h)e=d;else{if(256>h){if(e="\\x",16>h||256<h)e+="0"}else e="\\u",4096>h&&(e+="0");e+=h.toString(16).toUpperCase()}d=Aa[d]=e}h=d}f[g]=h}b.push('"');return b.join("")};var Ba,Ca,Ea,Fa;function Ga(){return u.navigator?u.navigator.userAgent:q}Fa=Ea=Ca=Ba=r;var Ha;if(Ha=Ga()){var Ia=u.navigator;Ba=0==Ha.indexOf("Opera");Ca=!Ba&&-1!=Ha.indexOf("MSIE");Ea=!Ba&&-1!=Ha.indexOf("WebKit");Fa=!Ba&&!Ea&&"Gecko"==Ia.product}var Ja=Ba,Ka=Ca,La=Fa,Ma=Ea,Na;
a:{var Oa="",Pa;if(Ja&&u.opera)var Qa=u.opera.version,Oa="function"==typeof Qa?Qa():Qa;else if(La?Pa=/rv\:([^\);]+)(\)|;)/:Ka?Pa=/MSIE\s+([^\);]+)(\)|;)/:Ma&&(Pa=/WebKit\/(\S+)/),Pa)var Ra=Pa.exec(Ga()),Oa=Ra?Ra[1]:"";if(Ka){var Sa,Ta=u.document;Sa=Ta?Ta.documentMode:l;if(Sa>parseFloat(Oa)){Na=String(Sa);break a}}Na=Oa}var Va={};
function Wa(a){var b;if(!(b=Va[a])){b=0;for(var c=String(Na).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",n=/(\d*)(\D*)/g,k=/(\d*)(\D*)/g;do{var p=n.exec(g)||["","",""],t=k.exec(h)||["","",""];if(0==p[0].length&&0==t[0].length)break;b=((0==p[1].length?0:parseInt(p[1],10))<(0==t[1].length?0:parseInt(t[1],10))?-1:(0==p[1].length?0:parseInt(p[1],10))>(0==t[1].length?
0:parseInt(t[1],10))?1:0)||((0==p[2].length)<(0==t[2].length)?-1:(0==p[2].length)>(0==t[2].length)?1:0)||(p[2]<t[2]?-1:p[2]>t[2]?1:0)}while(0==b)}b=Va[a]=0<=b}return b}var Xa={};function Ya(){return Xa[9]||(Xa[9]=Ka&&!!document.documentMode&&9<=document.documentMode)};function Za(a){Error.captureStackTrace?Error.captureStackTrace(this,Za):this.stack=Error().stack||"";a&&(this.message=String(a))}A(Za,Error);Za.prototype.name="CustomError";var E=Array.prototype,$a=E.indexOf?function(a,b,c){return E.indexOf.call(a,b,c)}:function(a,b,c){c=c==q?0:0>c?Math.max(0,a.length+c):c;if(x(a))return!x(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ab=E.map?function(a,b,c){return E.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=x(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},bb=E.some?function(a,b,c){return E.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,
e=x(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return m;return r};function cb(a,b){var c=db(a,b,l);return 0>c?q:x(a)?a.charAt(c):a[c]}function db(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1}function eb(a,b){var c=$a(a,b);0<=c&&E.splice.call(a,c,1)}function fb(a,b,c,d){E.splice.apply(a,gb(arguments,1))}function gb(a,b,c){return 2>=arguments.length?E.slice.call(a,b):E.slice.call(a,b,c)}
function hb(a,b){return a>b?1:a<b?-1:0};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function F(a,b){this.a=[];this.j=b||q}s=F.prototype;s.B=r;s.C=r;s.G=0;s.va=r;s.Ca=r;s.Ba=0;s.na=function(a,b){ib(this,a,b);this.G--;0==this.G&&this.B&&jb(this)};function ib(a,b,c){a.B=m;a.b=c;a.C=!b;jb(a)}function kb(a){a.B&&(a.va||j(new lb),a.va=r)}function G(a,b){kb(a);ib(a,m,b)}function H(a,b){kb(a);ib(a,r,b)}s.W=function(a,b){return this.z(a,q,b)};s.X=function(a,b){return this.z(q,a,b)};s.z=function(a,b,c){this.a.push([a,b,c]);this.B&&jb(this);return this};
function mb(a){return bb(a.a,function(a){return ja(a[1])})}function jb(a){a.d&&(a.B&&mb(a))&&(u.clearTimeout(a.d),delete a.d);a.g&&(a.g.Ba--,delete a.g);for(var b=a.b,c=r,d=r;a.a.length&&0==a.G;){var e=a.a.shift(),f=e[0],g=e[1],e=e[2];if(f=a.C?g:f)try{var h=f.call(e||a.j,b);v(h)&&(a.C=a.C&&(h==b||h instanceof Error),a.b=b=h);b instanceof F&&(d=m,a.G++)}catch(n){b=n,a.C=m,mb(a)||(c=m)}}a.b=b;d&&a.G&&(b.z(qa(a.na,a,m),qa(a.na,a,r)),b.Ca=m);c&&(a.d=u.setTimeout(function(){j(b)},0))}
function nb(a){var b=new F;G(b,a);return b}function lb(){Za.call(this)}A(lb,Za);lb.prototype.message="Deferred has already fired";lb.prototype.name="AlreadyCalledError";function ob(a,b){for(var c=ha(b),d=c?b:arguments,c=c?0:1;c<d.length&&!(a=a[d[c]],!v(a));c++);return a}var pb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function qb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<pb.length;f++)c=pb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function rb(a){return sb(a||arguments.callee.caller,[])}
function sb(a,b){var c=[];if(0<=$a(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(tb(a)+"(");for(var d=a.arguments,e=0;e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=tb(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(sb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function tb(a){if(ub[a])return ub[a];a=String(a);if(!ub[a]){var b=/function ([^\(]+)/.exec(a);ub[a]=b?b[1]:"[Anonymous]"}return ub[a]}var ub={};function vb(a,b,c,d,e){"number"==typeof e||wb++;d||ra();this.d=b;delete this.b;delete this.a}vb.prototype.b=q;vb.prototype.a=q;var wb=0;function xb(){}xb.prototype.a=q;xb.prototype.d=q;xb.prototype.b=q;function yb(a,b){this.name=a;this.value=b}yb.prototype.toString=ca("name");var zb=new yb("SEVERE",1E3),Ab=new yb("WARNING",900),Bb=new yb("INFO",800),Cb=new yb("CONFIG",700),Db=new yb("FINER",400),Eb=new yb("FINEST",300);function Fb(a){return a.d?a.d:a.a?Fb(a.a):q}
xb.prototype.log=function(a,b,c){if(a.value>=Fb(this).value){a="log:"+this.g(a,b,c).d;u.console&&(u.console.timeStamp?u.console.timeStamp(a):u.console.markTimeline&&u.console.markTimeline(a));u.msWriteProfilerMark&&u.msWriteProfilerMark(a);for(a=this;a;)a=a.a}};
xb.prototype.g=function(a,b,c){var d=new vb(0,String(b));if(c){d.b=c;var e;var f=arguments.callee.caller;try{var g;var h=fa("window.location.href");if(x(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:h,stack:"Not available"};else{var n,k,p=r;try{n=c.lineNumber||c.Ma||"Not available"}catch(t){n="Not available",p=m}try{k=c.fileName||c.filename||c.sourceURL||h}catch(B){k="Not available",p=m}g=p||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:n,
fileName:k,stack:c.stack||"Not available"}:c}e="Message: "+ta(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+ta(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+ta(rb(f)+"-> ")}catch(D){e="Exception trying to expose exception! You win, we lose. "+D}d.a=e}return d};function Gb(a,b){a.log(zb,b,l)}function I(a,b){a.log(Ab,b,l)}function J(a,b){a.log(Db,b,l)}function K(a,b){a.log(Eb,b,l)}var Hb={},Ib=q;
function L(a){Ib||(Ib=new xb,Hb[""]=Ib,Ib.d=Cb);var b;if(!(b=Hb[a])){b=new xb;var c=a.lastIndexOf("."),d=a.substr(c+1),c=L(a.substr(0,c));c.b||(c.b={});c.b[d]=b;b.a=c;Hb[a]=b}return b};function Jb(a){Error.captureStackTrace?Error.captureStackTrace(this,Jb):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.db.InvalidKeyException"}A(Jb,Error);function Kb(a){Error.captureStackTrace?Error.captureStackTrace(this,Kb):this.stack=Error().stack||"";a&&(this.message=String(a))}A(Kb,Error);Kb.prototype.name="ydn.db.InternalError";
function M(a){Error.captureStackTrace?Error.captureStackTrace(this,M):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="NotFoundError"}A(M,Error);M.prototype.name="NotFoundError";function Lb(a,b){Error.captureStackTrace?Error.captureStackTrace(this,Lb):this.stack=Error().stack||"";b&&(this.message=String(b));this.message+=" :"+a.message+" ["+a.code+"]";this.name="SQLError"}A(Lb,Error);
function Mb(a,b){Error.captureStackTrace?Error.captureStackTrace(this,Mb):this.stack=Error().stack||"";b&&(this.message=String(b));this.message+=" :"+a.message;this.name="SecurityError"}A(Mb,Error);function N(a,b,c){var d;z(a)?(d=a.store,b=a.id,a.parent!=q&&(c=new N(a.parent))):v(b)?d=a:(d=a.lastIndexOf("^|"),b=a,0<d&&(b=a.substr(d),c=new N(a.substring(0,d))),b=b.split("^:"),d=b[0],b=b[1],v(b)||j(Error("Invalid key value: "+a)));this.a=d;this.id=b;this.b=c||q}s=N.prototype;s.toJSON=function(){var a={store:this.a,id:this.id};this.b&&(a.parent=this.b.toJSON());return a};s.valueOf=function(){return(this.b?this.b.valueOf()+"^|":"")+this.a+"^:"+this.id};
s.toString=function(){return this.valueOf().replace("^|","|").replace("^:",":")};s.Ea=ca("a");s.Da=ca("id");s.Ia=ca("b");function Nb(a,b){this.r=a;this.a=b}Nb.prototype.m=L("ydn.db.req.RequestExecutor");Nb.prototype.c=q;function O(a,b,c,d){this.lower=a;this.upper=b;this.lowerOpen=!!c;this.upperOpen=!!d}s=O.prototype;s.lower=l;s.upper=l;s.lowerOpen=r;s.upperOpen=r;s.toJSON=function(){var a;a=this||{};return{lower:a.lower,upper:a.upper,lowerOpen:a.lowerOpen,upperOpen:a.upperOpen}};function Ob(a,b,c,d){return new O(a,b,c,d)}
function Pb(a){return a==q?q:v(a.upper)&&v(a.lower)?Qb.bound(a.lower,a.upper,!!a.lowerOpen,!!a.upperOpen):v(a.upper)?Qb.upperBound(a.upper,a.upperOpen):v(a.lower)?Qb.lowerBound(a.lower,a.lowerOpen):q}var Qb=u.IDBKeyRange||u.webkitIDBKeyRange||O;function Q(a){Error.captureStackTrace?Error.captureStackTrace(this,Q):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.ArgumentException"}A(Q,Error);function Rb(a){Error.captureStackTrace?Error.captureStackTrace(this,Rb):this.stack=Error().stack||"";a&&(this.message=String(a))}A(Q,Error);Rb.prototype.name="ydn.NotSupportedException";
function Sb(a){Error.captureStackTrace?Error.captureStackTrace(this,Sb):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.NotImplementedException"}A(Sb,Error);function Tb(a){Error.captureStackTrace?Error.captureStackTrace(this,Tb):this.stack=Error().stack||"";a&&(this.message=String(a))}A(Tb,Error);Tb.prototype.name="ydn.InternalError";
function Ub(a){Error.captureStackTrace?Error.captureStackTrace(this,Ub):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.ConstrainError"}A(Ub,Error);A(Q,Error);L("ydn");function Vb(a){if(!x(a)||/^[\s\xa0]*$/.test(a))return{};try{return JSON.parse(a)}catch(b){j(b)}};function Wb(a,b){Nb.call(this,a,b)}A(Wb,Nb);s=Wb.prototype;s.m=L("ydn.db.core.req.IndexedDb");s.I=function(a,b){function c(f){var g=d.c.objectStore(b[f]).count();g.onsuccess=function(d){e[f]=d.target.result;f++;f==b.length?G(a,e):c(f)};g.onerror=function(b){H(a,b)}}var d=this,e=[];0==b.length?G(a,[]):c(0)};s.ia=function(a,b,c,d){b=this.c.objectStore(b);var e;try{e=v(d)?b.put(c,d):b.put(c)}catch(f){j(f)}e.onsuccess=function(b){G(a,b.target.result)};e.onerror=function(b){H(a,b)}};
s.ja=function(a,b,c,d){function e(b){var k;try{k=v(d)?h.put(c[b],d[b]):h.put(c[b])}catch(p){j(p)}k.onsuccess=function(d){g++;f[b]=d.target.result;g==c.length?G(a,f):(d=b+10,d<c.length&&e(d))};k.onerror=function(b){g++;H(a,b)}}var f=[],g=0,h=this.c.objectStore(b);if(0<c.length)for(b=0;10>b&&b<c.length;b++)e(b);else G(a,[])};
s.Z=function(a,b,c){b=this.c.objectStore(b).openCursor(c);b.onsuccess=function(b){var c=b.target.result;c?(c=c["delete"](),c.onsuccess=function(){G(a,m)},c.onerror=function(){H(a,b)}):G(a,r)};b.onerror=function(b){H(a,b)}};s.A=function(a,b){for(var c=w(b)&&0<b.length?b:x(b)?[b]:Xb(this.a),d=c.length,e=0,f=0;f<d;f++){var g=this.c.objectStore(c[f]).clear();g.onsuccess=function(){e++;e==d&&G(a,m)};g.onerror=function(b){e++;e==d&&H(a,b)}}};
function Yb(a,b,c,d,e,f,g,h,n){var k=[];a=a.c.objectStore(c);f=Zb(f,n);d=d?a.index(d).openCursor(e,f):a.openCursor(e,f);var p=r;d.onsuccess=function(a){(a=a.target.result)?!p&&0<h?(p=m,a.advance(h)):(k.push(a.value),k.length<g?a.advance(1):G(b,k)):G(b,k)};d.onerror=function(a){H(b,a)}}s.fa=function(a,b,c,d,e,f){Yb(this,a,b,q,c,d,e,f)};s.ea=function(a,b,c,d,e,f,g,h){Yb(this,a,b,c,d,e,f,g,h)};
s.ra=function(a,b,c,d,e,f){var g=[];b=this.c.objectStore(b).openCursor(c,Zb(d));var h=r;b.onsuccess=function(b){(b=b.target.result)?!h&&0<f?(h=m,b.advance(f)):(g.push(b.key),g.length<e?b.advance(1):G(a,g)):G(a,g)};b.onerror=function(b){H(a,b)}};s.sa=function(a,b,c,d,e){var f=[];b=this.c.objectStore(b).openCursor(q,Zb(c));var g=r;b.onsuccess=function(b){(b=b.target.result)?!g&&0<e?(g=m,b.advance(e)):(f.push(b.primaryKey),f.length<d?b.advance(1):G(a,f)):G(a,f)};b.onerror=function(b){H(a,b)}};
s.qa=function(a,b,c,d,e,f,g,h){var n=[];b=this.c.objectStore(b).index(c).openKeyCursor(d,Zb(e,h));var k=r;b.onsuccess=function(b){(b=b.target.result)?!k&&0<g?(k=m,b.advance(g)):(n.push(b.primaryKey),n.length<f&&b.advance(1)):G(a,n)};b.onerror=function(b){H(a,b)}};s.L=function(a,b,c){var d;try{d=this.c.objectStore(b)}catch(e){"NotFoundError"==e.name&&j(new M(b+" not in Tx scope: ?")),j(e)}b=d.get(c);b.onsuccess=function(b){G(a,b.target.result)};b.onerror=function(b){H(a,b)}};
s.da=function(a,b,c){function d(b){if(c[b]==q)if(f++,e[b]=l,f==h)G(a,e);else{var k=b+10;k<h&&d(k)}var p;try{p=g.get(c[b])}catch(t){"DataError"==t.name&&j(new Jb(c[b])),j(t)}p.onsuccess=function(c){f++;e[b]=c.target.result;f==h?G(a,e):(c=b+10,c<h&&d(c))};p.onerror=function(b){f++;H(a,b)}}var e=[],f=0,g=this.c.objectStore(b),h=c.length;if(0<h)for(b=0;10>b&&b<h;b++)d(b);else G(a,[])};
s.ga=function(a,b){function c(g){var n=b[g],k=d.c.objectStore(n.a),p;try{p=k.get(n.id)}catch(t){"DataError"==t.name&&j(new Jb(n+" at "+g)),j(t)}p.onsuccess=function(d){f++;e[g]=d.target.result;f==b.length?G(a,e):(d=g+10,d<b.length&&c(d))};p.onerror=function(b){f++;H(a,b)}}var d=this,e=[],f=0;if(0<b.length)for(var g=0;10>g&&g<b.length;g++)c(g);else G(a,[])};
s.$=function(a,b,c,d){b=this.c.objectStore(b);v(d)?(d=b.index(d),c=c===q?d.count():d.count(c)):c=c===q?b.count():b.count(c);c.onsuccess=function(b){G(a,b.target.result)};c.onerror=function(b){H(a,b)}};function $b(){0!=ac&&ka(this)}var ac=0;!Ka||Ya();var bc=!Ka||Ya(),cc=Ka&&!Wa("9");!Ma||Wa("528");La&&Wa("1.9b")||Ka&&Wa("8")||Ja&&Wa("9.5")||Ma&&Wa("528");La&&!Wa("8")||Ka&&Wa("9");function R(a,b){this.type=a;this.a=this.target=b}R.prototype.b=r;R.prototype.d=m;R.prototype.g=function(){this.d=r};function dc(a){dc[" "](a);return a}dc[" "]=ba();function ec(a,b){a&&fc(this,a,b)}A(ec,R);ec.prototype.target=q;ec.prototype.j=q;function fc(a,b,c){var d=a.type=b.type;R.call(a,d);a.target=b.target||b.srcElement;a.a=c;if((c=b.relatedTarget)&&La)try{dc(c.nodeName)}catch(e){}a.j=b;b.defaultPrevented&&a.g();delete a.b}ec.prototype.g=function(){ec.xa.g.call(this);var a=this.j;if(a.preventDefault)a.preventDefault();else if(a.returnValue=r,cc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};function gc(){}var hc=0;gc.prototype.key=0;gc.prototype.t=r;gc.prototype.a=r;gc.prototype.handleEvent=function(a){return this.b?this.D.call(this.ba||this.src,a):this.D.handleEvent.call(this.D,a)};var ic={},S={},jc={},kc={};
function lc(a,b,c,d,e){if(b)if(w(b))for(var f=0;f<b.length;f++)lc(a,b[f],c,d,e);else{d=!!d;var g=S;b in g||(g[b]={l:0,k:0});g=g[b];d in g||(g[d]={l:0,k:0},g.l++);var g=g[d],h=ka(a),n;g.k++;if(g[h]){n=g[h];for(f=0;f<n.length;f++)if(g=n[f],g.D==c&&g.ba==e){if(g.t)break;return}}else n=g[h]=[],g.l++;var k=mc,p=bc?function(a){return k.call(p.src,p.key,a)}:function(a){a=k.call(p.src,p.key,a);if(!a)return a},f=p;f.src=a;var t=g=new gc;ja(c)?t.b=m:c&&c.handleEvent&&ja(c.handleEvent)?t.b=r:j(Error("Invalid listener argument"));
t.D=c;t.d=f;t.src=a;t.type=b;t.capture=!!d;t.ba=e;t.a=r;t.key=++hc;t.t=r;c=g.key;f.key=c;n.push(g);ic[c]=g;jc[h]||(jc[h]=[]);jc[h].push(g);a.addEventListener?(a==u||!a.oa)&&a.addEventListener(b,f,d):a.attachEvent(b in kc?kc[b]:kc[b]="on"+b,f)}else j(Error("Invalid event type"))}
function nc(a,b,c,d,e){if(w(b))for(var f=0;f<b.length;f++)nc(a,b[f],c,d,e);else{d=!!d;a:{f=S;if(b in f&&(f=f[b],d in f&&(f=f[d],a=ka(a),f[a]))){a=f[a];break a}a=q}if(a)for(f=0;f<a.length;f++)if(a[f].D==c&&a[f].capture==d&&a[f].ba==e){oc(a[f].key);break}}}
function oc(a){if(ic[a]){var b=ic[a];if(!b.t){var c=b.src,d=b.type,e=b.d,f=b.capture;c.removeEventListener?(c==u||!c.oa)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in kc?kc[d]:kc[d]="on"+d,e);c=ka(c);jc[c]&&(e=jc[c],eb(e,b),0==e.length&&delete jc[c]);b.t=m;if(b=S[d][f][c])b.ta=m,pc(d,f,c,b);delete ic[a]}}}
function pc(a,b,c,d){if(!d.N&&d.ta){for(var e=0,f=0;e<d.length;e++)d[e].t?d[e].d.src=q:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.ta=r;0==f&&(delete S[a][b][c],S[a][b].l--,0==S[a][b].l&&(delete S[a][b],S[a].l--),0==S[a].l&&delete S[a])}}function qc(a,b,c,d,e){var f=1;b=ka(b);if(a[b]){a.k--;a=a[b];a.N?a.N++:a.N=1;try{for(var g=a.length,h=0;h<g;h++){var n=a[h];n&&!n.t&&(f&=rc(n,e)!==r)}}finally{a.N--,pc(c,d,b,a)}}return Boolean(f)}function rc(a,b){a.a&&oc(a.key);return a.handleEvent(b)}
function sc(a,b){var c=b.type||b,d=S;if(c in d){if(x(b))b=new R(b,a);else if(b instanceof R)b.target=b.target||a;else{var e=b;b=new R(c,a);qb(b,e)}var e=1,f,d=d[c],c=m in d,g;if(c){f=[];for(g=a;g;g=q)f.push(g);g=d[m];g.k=g.l;for(var h=f.length-1;!b.b&&0<=h&&g.k;h--)b.a=f[h],e&=qc(g,f[h],b.type,m,b)&&b.d!=r}if(r in d)if(g=d[r],g.k=g.l,c)for(h=0;!b.b&&h<f.length&&g.k;h++)b.a=f[h],e&=qc(g,f[h],b.type,r,b)&&b.d!=r;else for(d=a;!b.b&&d&&g.k;d=q)b.a=d,e&=qc(g,d,b.type,r,b)&&b.d!=r}}
function mc(a,b){if(!ic[a])return m;var c=ic[a],d=c.type,e=S;if(!(d in e))return m;var e=e[d],f,g;if(!bc){f=b||fa("window.event");var h=m in e,n=r in e;if(h){if(0>f.keyCode||f.returnValue!=l)return m;a:{var k=r;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(p){k=m}if(k||f.returnValue==l)f.returnValue=m}}k=new ec;fc(k,f,this);f=m;try{if(h){for(var t=[],B=k.a;B;B=B.parentNode)t.push(B);g=e[m];g.k=g.l;for(var D=t.length-1;!k.b&&0<=D&&g.k;D--)k.a=t[D],f&=qc(g,t[D],d,m,k);if(n){g=e[r];g.k=g.l;for(D=0;!k.b&&
D<t.length&&g.k;D++)k.a=t[D],f&=qc(g,t[D],d,r,k)}}else f=rc(c,k)}finally{t&&(t.length=0)}return f}d=new ec(b,this);return f=rc(c,d)};function tc(){$b.call(this)}A(tc,$b);tc.prototype.oa=m;tc.prototype.addEventListener=function(a,b,c,d){lc(this,a,b,c,d)};tc.prototype.removeEventListener=function(a,b,c,d){nc(this,a,b,c,d)};var uc=u.window||u.self;function vc(a,b,c){ja(a)?c&&(a=qa(a,c)):a&&"function"==typeof a.handleEvent?a=qa(a.handleEvent,a):j(Error("Invalid listener argument"));2147483647<b||uc.setTimeout(a,b||0)};function wc(a,b){Nb.call(this,a,b)}A(wc,Nb);s=wc.prototype;s.ia=function(a,b,c,d){b=xc(this.c,c,b,d);G(a,b)};s.ja=function(a,b,c,d){for(var e=[],f=0;f<c.length;f++)e[f]=xc(this.c,c[f],b,v(d)?d[f]:l);G(a,e)};s.L=function(a,b,c){G(a,yc(this.c,b,c))};s.da=function(a,b,c){for(var d=[],e=0;e<c.length;e++){var f=yc(this.c,b,c[e]);d.push(f)}G(a,d)};s.ga=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=yc(this.c,b[d].a,b[d].id);c.push(e)}G(a,c)};s.ea=ba();s.Z=function(a,b,c){zc(this.c,b,c);G(a,m)};
s.A=function(a,b){for(var c=x(b)?[b]:b,d=0;d<c.length;d++)zc(this.c,c[d]);G(a,m)};s.I=function(a,b){vc(function(){for(var c=[],d=0;d<b.length;d++){var e=Ac(this.c,b[d]);c[d]=e.length}G(a,c)},0,this)};s.$=function(a,b){var c="_database_"+this.r;v(b)&&(c+="-"+b);var d=0,e;for(e in this.c)this.c.hasOwnProperty(e)&&0==e.lastIndexOf(c,0)&&d++;G(a,d)};function Bc(a,b){Nb.call(this,a,b)}A(Bc,Nb);s=Bc.prototype;s.m=L("ydn.db.core.req.WebSql");function Cc(a,b){var c=Vb(a._default_);if(b.keyPath!=q)for(var d=Dc(a[b.keyPath],b.type),e=c,f=0;f<b.a.length;f++){var g=b.a[f];if(f==b.a.length-1){e[g]=d;break}v(e[g])||(e[g]={});e=e[g]}for(d=0;d<b.indexes.length;d++)e=b.indexes[d],"_default_"!=e.name&&(c[e.name]=Dc(a[e.name],e.type));return c}s.ra=function(a,b,c,d,e,f){Ec(this,a,m,b,l,c,d,e,f)};s.qa=function(a,b,c,d,e,f,g){Ec(this,a,m,b,c,d,e,f,g)};
function Ec(a,b,c,d,e,f,g,h,n){var k=[],p=T(a.a,d);e=v(e)?e:x(p.keyPath)?p.keyPath:"_ROWID_";d=C(e);var t=x(p.keyPath)?p.keyPath:"_ROWID_",B="SELECT "+(c?C(t):"*")+" FROM "+C(p.name),D=[];if(f!==q){var Z="",P=[];f&&(e=C(e),(f==q?0:v(f.lower)&&v(f.upper)&&!f.lowerOpen&&!f.upperOpen&&f.lower.length==f.upper.length+1&&"\uffff"==f.upper[f.lower.length-1])?(Z=e+" LIKE ?",P.push(f.lower+"%")):f.lower==f.upper?(Z=e+" = ?",P.push(f.lower)):(v(f.lower)&&(Z+=" "+e+(f.lowerOpen?" > ":" >= ")+"?",P.push(f.lower)),
v(f.upper)&&(Z+=(0<Z.length?" AND ":" ")+e+(f.upperOpen?" < ":" <= ")+"?",P.push(f.upper))));B+=" WHERE "+Z;for(f=0;f<P.length;f++)D[f]=Fc(P[f],p.type)}B+=" ORDER BY "+d+" "+(g?"DESC":"ASC");y(h)&&(B+=" LIMIT "+h);y(n)&&(B+=" OFFSET "+n);a.c.executeSql(B,D,function(a,d){for(var e=0,f=d.rows.length;e<f;e++){var g=d.rows.item(e);c?k[e]=Dc(g[t],p.type):g!=q&&(k[e]=Cc(g,p))}G(b,k)},function(c,d){I(a.m,"get error: "+d.message);H(b,d);return m})}s.sa=function(a,b,c,d,e){Ec(this,a,m,b,l,q,c,d,e)};
s.ia=function(a,b,c,d){var e=T(this.a,b);e||j(new M(b));var f=this,g=Gc(e,c,d);b="INSERT OR REPLACE INTO "+C(e.name)+" ("+g.ma.join(", ")+") VALUES ("+g.wa.join(", ")+");";this.c.executeSql(b,g.za,function(b,c){G(a,v(g.key)?g.key:c.insertId)},function(b,c){I(f.m,"put error: "+c.message);H(a,c);return m})};
s.ja=function(a,b,c,d){function e(b,k){var p;p=v(d)?Gc(f,c[b],d[b]):Gc(f,c[b]);var t="INSERT OR REPLACE INTO "+C(f.name)+" ("+p.ma.join(", ")+") VALUES ("+p.wa.join(", ")+");";k.executeSql(t,p.za,function(d,f){h++;g[b]=v(p.key)?p.key:f.insertId;if(h==c.length)G(a,g);else{var k=b+2;k<c.length&&e(k,d)}},function(b,c){H(a,c);return m})}var f=T(this.a,b);f||j(new M(b));var g=[],h=0;if(0<c.length)for(b=0;2>b&&b<c.length;b++)e(b,this.c);else G(a,[])};
s.L=function(a,b,c){var d=T(this.a,b),e=this;b=Hc(d);c=[Fc(c,d.type)];b="SELECT * FROM "+C(d.name)+" WHERE "+b+" = ?";this.c.executeSql(b,c,function(b,c){if(0<c.rows.length){var e=c.rows.item(0);e!=q?G(a,Cc(e,d)):G(a,l)}else G(a,l)},function(b,c){I(e.m,"get error: "+c.message);H(a,c);return m})};
s.da=function(a,b,c){function d(b,k){var p=c[b],t=Hc(h),p=[Fc(p,h.type)],t="SELECT * FROM "+C(h.name)+" WHERE "+t+" = ?";k.executeSql(t,p,function(e,k){g++;if(0<k.rows.length){var p=k.rows.item(0);p!=q&&(f[b]=Cc(p,h))}else f[b]=l;g==c.length?G(a,f):(p=b+10,p<c.length&&d(p,e))},function(b,c){I(e.m,"get error: "+c.message);H(a,c);return m})}var e=this,f=[],g=0,h=T(this.a,b);if(0<c.length)for(b=0;10>b&&b<c.length;b++)d(b,this.c);else G(a,[])};s.fa=function(a,b,c,d,e,f){Ec(this,a,r,b,l,c,d,e,f)};
s.ea=ba();s.ga=function(a,b){function c(g,n){var k=b[g],p=T(d.a,k.a),k=w(k.id)?k.id.join("^|"):k.id;Hc(p);var k=[k],t="SELECT * FROM "+C(p.name)+" WHERE "+Ic(p)+" = ?";n.executeSql(t,k,function(d,k){f++;if(0<k.rows.length){var n=k.rows.item(0);n!=q&&(e[g]=Cc(n,p))}else e[g]=l;f==b.length?G(a,e):(n=g+10,n<b.length&&c(n,d))},function(b,c){I(d.m,"get error: "+c.message);H(a,c);return m})}var d=this,e=[],f=0;if(0<b.length)for(var g=0;10>g&&g<b.length;g++)c(g,this.c);else G(a,[])};
s.A=function(a,b){function c(b,g){var h=T(d.a,e[b]);h||j(new M(e[b]));h="DELETE FROM  "+C(h.name);g.executeSql(h,[],function(d){b==e.length-1?G(a,m):c(b+1,d)},function(b,c){I(d.m,"Sqlite error: "+c.message);H(a,c);return m})}var d=this,e=w(b)&&0<b.length?b:x(b)?[b]:Xb(this.a);0<e.length?c(0,this.c):G(a,[])};
s.Z=function(a,b,c){var d=T(this.a,b);d||j(new M(b));var e=this;b="DELETE FROM "+C(d.name)+" WHERE "+Ic(d)+" = ?";this.c.executeSql(b,[c],function(){G(a,m)},function(b,c){I(e.m,"put error: "+c.message);H(a,c);return m})};
s.I=function(a,b){function c(f){var g="SELECT COUNT(*) FROM "+C(b[f]);d.c.executeSql(g,[],function(d,g){var k=g.rows.item(0);e[f]=parseInt(k["COUNT(*)"],10);f++;f==b.length?G(a,e):c(f)},function(b,c){I(d.m,"count error: "+c.message);H(a,c);return m})}var d=this,e=[];0==b.length?G(a,0):c(0);return a};
s.$=function(a,b){var c=this,d="SELECT COUNT(*) FROM "+C(b);this.c.executeSql(d,[],function(b,c){var d=c.rows.item(0);G(a,d["COUNT(*)"])},function(b,d){I(c.m,"count error: "+d.message);H(a,d);return m});return a};s.toString=function(){return"WebSqlEx:"+(this.r||"")};/*
 _try.
*/
function Jc(a){this.b=a;this.g=[];this.F=new Kc}s=Jc.prototype;s.La=L("ydn.db.tr.TxStorage");s.la=function(){return this.b.la()};s.Y=function(a){return this.b.Y(a)};s.v=function(a,b,c,d){this.b.v(a,b,c,d)};s.F=q;s.V=ca("b");s.type=function(){return this.b.type()};
s.H=function(a,b,c,d,e){var f=a.name||"",g=b;x(b)?g=[b]:(!w(b)||0<b.length&&!x(b[0]))&&j(new Q("storeNames"));var h=v(c)?c:U,n=a;if(4<arguments.length){var k=Array.prototype.slice.call(arguments,4),n=function(){var b=Array.prototype.slice.call(arguments),b=b.concat(k);return a.apply(this,b)};n.name=f}var p=this;this.F.a?this.g.push({aa:4<arguments.length?n:a,Ha:b,mode:h,o:d}):this.b.v(function(a){p.j=m;var b=p.F;b.a=a;b.d=r;b.o=q;K(b.b,b+": open");n(p)},g,h,function(a,b){try{ja(d)&&d(a,b)}catch(c){}finally{var e=
p.F;e.a?(K(e.b,e+": close"),e.a=q,ja(e.o)&&e.o(a,b),e.o=q):I(e.b,e+" has no TX to be unlocked for "+a);p.j=r;var e=p,f=e.g.shift();f&&e.H(f.aa,f.Ha,f.mode,f.o);ra()}})};s.toString=function(){return"ydn.db.tr.TxStorage:"+this.b.w()};function V(a,b,c,d){Jc.call(this,a);this.a=d}A(V,Jc);s=V.prototype;s.V=function(){return V.xa.V.call(this)};s.w=function(){return this.d=this.d||this.V().w()};s.s=q;function Lc(a){if(a.s)return a.s;var b=a.type();"indexeddb"==b?a.s=new Wb(a.w(),a.a):"websql"==b?a.s=new Bc(a.d,a.a):"memory"==b||"localstorage"==b||"sessionstorage"==b?a.s=new wc(a.d,a.a):j(new Kb("No executor for "+b));return a.s}
function W(a,b,c,d,e){var f=a.F;if(f.a&&!f.d)Lc(a).c=f.a,b(Lc(a));else{var g=function(){a.K=m;f.a||j(new Kb("Tx not active for scope: "+e));f.d&&j(new Kb("Tx not available for scope: "+e));Lc(a).c=f.a;b(Lc(a));K(f.b,f+": locked");f.d=m};g.name=e;a.H(g,c,d,ba())}}
s.R=function(a,b,c){var d=new F,e,f,g;if(v(a))if(w(a)){(v(c)||v(b))&&j(new Q("too many arguments."));e=a;for(a=0;a<e.length;a++)Mc(this.a,e[a])||j(new M(e[a]));W(this,function(a){a.I(d,e)},e,U,"countStores")}else x(a)?(Mc(this.a,a)||j(new M(a)),e=[a],x(b)?(f=b,g=Pb(c)):z(b)||!v(b)?(v(c)&&j(new Q),g=Pb(b)):j(new Q("key range")),W(this,function(a){a.$(d,e[0],g,f)},e,U,"countKeyRange")):j(new Q);else{(v(c)||v(b))&&j(new Q("too many arguments."));e=Xb(this.a);var h=new F;W(this,function(a){a.I(d,e)},
e,U,"countStores");d.z(function(a){a=a.reduce(function(a,b){return b+a},0);G(h,a)},function(a){H(h,a)});return h}return d};s.S=function(a,b){var c=new F;if(a instanceof N){var d=a.a;if(!Mc(this.a,d)){if(this.a.a())return nb(l);j(new Q("Store: "+d+" not found."))}var e=a.id;W(this,function(a){a.L(c,d,e)},[d],U,"getById")}else if(x(a)&&v(b)){if(!T(this.a,a)){if(this.a.a())return nb(l);j(new Q("Store: "+a+" not found."))}W(this,function(d){d.L(c,a,b)},[a],U,"getById")}else j(new Q);return c};
s.keys=function(a,b,c,d,e,f,g){var h,n,k,p,t,B=new F;!v(b)||ia(b)?(p=!!b,y(c)?n=c:(v(c)&&j(new TypeError("arg3")),n=1E6),y(d)?k=d:(v(d)&&j(new TypeError("arg4")),k=0),W(this,function(b){b.sa(B,a,p,n,k)},[a],U,"keysByStore")):z(b)||b===q?(z(b)&&(h=Pb(b)),ia(c)||!v(c)?(p=!!c,y(d)?n=d:(v(d)&&j(new Q("arg4 must be number|undefined.")),n=1E6),y(e)?k=e:(v(e)&&j(new Q("arg5 must be number|undefined.")),k=0),(v(f)||v(g))&&j(new Q("too many arguments")),W(this,function(b){b.ra(B,a,h,p,n,k)},[a],U,"keysByKeyRange")):
j(new Q("arg3 must be boolean|string|undefined."))):x(b)?(!v(c)||c===q||z(c)?h=Pb(c):j(new Q("arg3 must be IDBKeyRange|null|undefined.")),v(d)&&!ia(d)&&j(new Q("arg4 must be boolean|undefined.")),p=!!d,y(e)?n=e:(v(e)&&j(new Q("arg5 must be number|undefined.")),n=1E6),y(f)?k=f:(v(f)&&j(new Q("arg6 must be number|undefined.")),k=0),v(g)&&!ia(g)&&j(new Q("arg7 must be boolean|undefined.")),t=!!g,W(this,function(c){c.qa(B,a,b,h,p,n,k,t)},[a],U,"keysByIndexKeyRange")):j(new Q);return B};
s.T=function(a,b,c,d,e,f,g){var h=new F,n,k,p,t;if(x(a)){if(!T(this.a,a)){if(this.a.a())return nb(l);j(new Q("Store: "+a+" not found."))}if(w(b))W(this,function(c){c.da(h,a,b)},[a],U,"listByIds");else if(!v(b)||ia(b))n=!!b,v(c)?y(c)?k=c:j(new Q("arg3 must be number|undefined.")):k=1E6,v(d)?y(d)?p=d:j(new Q("arg4 must be number|undefined.")):p=0,v(e)&&j(new Q("too many input arguments")),W(this,function(b){b.fa(h,a,q,n,k,p)},[a],U,"listByKeyRange");else if(z(b)||b===q||!v(b)){var B=Pb(b);v(c)&&!ia(c)&&
j(new Q("arg3 must be boolean|undefined."));n=!!c;v(d)?y(d)?k=d:j(new Q("arg4 must be number|undefined.")):k=1E6;v(e)?y(e)?p=e:j(new Q("arg5 must be number|undefined.")):p=0;var D=B;W(this,function(b){b.fa(h,a,D,n,k,p)},[a],U,"listByKeyRange")}else x(b)?(B=Pb(c),v(d)&&!ia(d)&&j(new Q("arg4 must be boolean|undefined.")),n=!!d,v(e)?y(e)?k=e:j(new Q("arg5 must be number|undefined.")):k=1E6,v(f)?y(f)?p=f:j(new Q("arg6 must be number|undefined.")):p=0,t=!!g,v(g)&&!ia(g)&&j(new Q("arg7 must be boolean|undefined.")),
W(this,function(c){c.ea(h,a,b,B,n,k,p,t)},[a],U,"listByKeyRange")):j(new Q("arg2"))}else if(w(a))if(a[0]instanceof N){c=[];for(d=0;d<a.length;d++){e=a[d].a;if(!Mc(this.a,e)){if(this.a.a())return c=[],c[a.length-1]=l,nb(c);j(new Q("Store: "+e+" not found."))}0<=$a(c,e)||c.push(e)}W(this,function(b){b.ga(h,a)},c,U,"listByKeys")}else j(new Q("must be array of ydn.db.Key"));else j(new Q);return h};
s.U=function(a,b,c){var d=x(a)?a:z(a)?a.name:l;x(d)||j(new Q("store name"));var e=T(this.a,d);e?this.a.a()&&z(a)&&(a=Nc(a),(a=Oc(e,a))&&j(new Rb("schema change: "+a))):(this.a.a()||j(new Q("Not found: "+d)),e=Nc(z(a)?a:{name:d}),K(this.La,"Adding object store: "+d),this.Y(e));var f=new F;e||j(new Q("Store: "+d+" not exists."));x(e.keyPath)&&v(c)&&j(new Q("key cannot provide while in-line key is in used."));e.autoIncrement&&v(c)&&j(new Q("key cannot provide while autoIncrement is true."));!x(e.keyPath)&&
(!e.autoIncrement&&!v(c))&&j(new Q("out-of-line key must be provided."));w(b)?W(this,function(a){a.ja(f,d,b,c)},[d],Pc,"putObjects"):z(b)?W(this,function(a){a.ia(f,d,b,c)},[d],Pc,"putObject"):j(new Q);return f};
s.clear=function(a,b){var c=new F;if(x(a))x(b)||y(b)||w(b)?W(this,function(d){d.Z(c,a,b)},[a],Pc,"clearById"):(v(b)&&j(new Q),W(this,function(b){b.A(c,a)},[a],Pc,"clearByStore"));else if(w(a)&&x(a[0])){var d=a;W(this,function(a){a.A(c,d)},d,Pc,"clearByStore")}else v(a)&&j(new Q),d=Xb(this.a),W(this,function(a){a.A(c,d)},d,Pc,"clearByStore");return c};s.toString=function(){return"TxStorage:"+this.V().w()};var Qc={READ_ONLY:"readonly",READ_WRITE:"readwrite",VERSION_CHANGE:"versionchange"},Rc=u.webkitIDBRequest&&"LOADING"in u.webkitIDBRequest?u.webkitIDBTransaction||u.IDBTransaction:Qc,U=Rc.READ_ONLY,Pc=Rc.READ_WRITE,Sc=Rc.VERSION_CHANGE;function Zb(a,b){return a?b?"prevunique":"prev":b?"nextunique":"next"};var Tc={};
function Uc(a){a=[a];for(var b=new Vc,c=0,d,e;(e=a.pop())!==l;){0===c%4&&12<c+4&&(b.write(c),c=0);d=typeof e;if(e instanceof Array)if(c+=4,0<e.length){a.push(Tc);for(d=e.length;d--;)a.push(e[d]);continue}else b.write(c);else if("number"===d)c+=1,b.write(c),Wc(b,e);else if(e instanceof Date)c+=2,b.write(c),Wc(b,e.valueOf());else if("string"===d){c+=3;b.write(c);c=b;for(d=0;d<e.length;d++){var f=e.charCodeAt(d);126>=f?c.write(f+1):16510>=f?(f-=127,c.write(128|f>>8,f&255)):c.write(192|f>>10,f>>2|255,
(f|3)<<6)}c.write(0)}else if(e===Tc)b.write(0);else return"";c=0}return b.a().toString()}
function Wc(a,b){var c,d,e;c=b;var f=e=d=0;if(0!==c)if(isFinite(c)){0>c&&(d=1,c=-c);f=0;if(2.2250738585072014E-308<=c){for(e=c;1>e;)f--,e*=2;for(;2<=e;)f++,e/=2;e=f+1023}f=e?Math.floor(4503599627370496*(c/Math.pow(2,f)-1)):Math.floor(c/4.9E-324)}else e=2047,isNaN(c)?f=0x8000000000000:-Infinity===c&&(d=1);c=d;d=e;e=f;c&&(e=0xfffffffffffff-e,d=2047-d);a.write((c?0:128)|d>>4);a.write((d&15)<<4|0|e/281474976710656);e%=281474976710656;c=0|e/4294967296;a.write(c>>8,c&255);e%=4294967296;c=0|e/65536;a.write(c>>
8,c&255);c=e%65536;a.write(c>>8,c&255)}function Xc(a){var b=a.q()|0,c=b>>7?r:m,d=c?-1:1,e=(b&127)<<4,b=a.q()|0,e=e+(b>>4);c&&(e=2047-e);for(var b=[c?15-(b&15):b&15],f=6;f--;)b.push(c?255-(a.q()|0):a.q()|0);a=0;for(f=7;f--;)a=a/256+b[f];a/=16;return 0===a&&0===e?0:(a+1)*Math.pow(2,e-1023)*d}
function Yc(a){for(var b=[],c=0,d=0,e=0,f,g;;){f=a.q();if(0===f||f==q)break;0===c?(g=f>>6,2>g&&!isNaN(f)?b.push(String.fromCharCode(f-1)):(c=g,d=f<<10,e++)):2===c?(b.push(String.fromCharCode(d+f+127)),c=d=e=0):2===e?(d+=f<<2,e++):(b.push(String.fromCharCode(d|f>>6)),c=d=e=0)}return b.join("")}function Zc(a){this.a=q;var b=a.length-1,c=-1;this.q=function(){return this.a=c<b?parseInt(a[++c]+a[++c],16):q}}
function Vc(){var a=[],b;this.write=function(c){for(var d=0;d<arguments.length;d++)b=arguments[d].toString(16),a.push(2===b.length?b:b="0"+b)};this.toString=function(){return a.length?a.join(""):q};this.a=function(){for(var b=a.length;"00"===a[--b];);a.length=++b;return this}};function $c(a,b,c,d,e){!v(a)&&v(e)&&(a=e);ha(a)?(a=ab(a,function(a){return a}),v(e)||(e=a.join(", "))):x(a)||j(new Q("index keyPath or name required."));this.keyPath=a;this.name=v(e)?e:this.keyPath;this.type=ad(b);this.type!=b&&j(new Q("Invalid index type: "+b+" in "+this.name));this.unique=!!c;this.multiEntry=!!d}var bd=String.fromCharCode(31);
function Fc(a,b){if("DATE"==b){if(a instanceof Date)return+a}else{if("ARRAY"==b){var c=a==q?[""]:w(a)?a:[a],d=c[0]instanceof Date?"d":y(c[0])?"n":"t",c="d"==d?c.reduce(function(a,b){return a+ +b},""):c.join(bd);return d+bd+c+bd}return v(b)?a:"X'"+Uc(a)+"'"}}
function Dc(a,b){if("DATE"==b)return new Date(a);if("ARRAY"==b){var c=a.split(bd),d=c[0],c=c.slice(1,c.length-1);return ab(c,function(a){return"d"==d?new Date(parseInt(a,10)):"n"==d?parseFloat(a):a})}if(v(b))c=a;else{for(var e=c=[],f,g=[],h,n,k=new Zc(a);k.q()!=q;)if(0===k.a)e=g.pop();else{if(k.a===q)break;do{h=k.a/4|0;f=k.a%4;for(var p=0;p<h;p++)n=[],e.push(n),g.push(e),e=n;if(0===f&&12<k.a+4)k.q();else break}while(1);1===f?e.push(Xc(k)):2===f?e.push(new Date(Xc(k))):3===f?e.push(Yc(k)):0===f&&(e=
g.pop())}c=c[0]}return c}var cd="ARRAY BLOB DATE INTEGER NUMERIC TEXT".split(" ");function ad(a){a=$a(cd,a);return cd[a]}$c.prototype.toJSON=function(){return{name:this.name,keyPath:this.keyPath,type:this.type,unique:this.unique,multiEntry:this.multiEntry}};
function dd(a,b,c,d,e){this.name=a;x(this.name)||j(new Q("store name must be a string"));this.keyPath=v(b)?b:q;this.keyPath!==q&&(!x(this.keyPath)||w(this.keyPath))&&j(new Q("keyPath must be a string or array"));this.autoIncrement=c;var f;v(d)&&(f=ad(d),v(f)||j(new Q("type invalid in store: "+this.name)));this.type=v(f)?f:this.autoIncrement?"INTEGER":l;this.a=x(this.keyPath)?this.keyPath.split("."):[];this.indexes=e||[]}
dd.prototype.toJSON=function(){for(var a=[],b=0;b<this.indexes.length;b++)a.push(this.indexes[b].toJSON());return{name:this.name,keyPath:this.keyPath,autoIncrement:this.autoIncrement,type:this.type,indexes:a}};function Nc(a){var b=[],c=a.indexes||[];if(w(c))for(var d=0;d<c.length;d++){var e=new $c(c[d].keyPath,c[d].type,c[d].unique,c[d].multiEntry,c[d].name);v(e.keyPath)&&e.keyPath===a.keyPath||b.push(e)}return new dd(a.name,a.keyPath,a.autoIncrement,a.type,b)}
function ed(a,b){return cb(a.indexes,function(a){return a.name==b})}function fd(a,b){return b==a.keyPath?m:bb(a.indexes,function(a){return a.name==b})}function Ic(a){return x(a.keyPath)?C(a.keyPath):l}function Hc(a){return x(a.keyPath)?C(a.keyPath):"_ROWID_"}
function Gc(a,b,c){var d=[];c=v(c)?c:x(a.keyPath)?ob(b,a.a):l;var e=[];v(c)&&(e=a.keyPath!=q?[Ic(a)]:["_ROWID_"],d=[Fc(c,a.type)]);for(var f=0;f<a.indexes.length;f++)if(!(a.indexes[f].name==a.keyPath||"_default_"==a.indexes[f].name)){var g=b[a.indexes[f].name];v(g)&&(d.push(Fc(g,a.indexes[f].type)),e.push(C(a.indexes[f].name)))}var f={},h;for(h in b)b.hasOwnProperty(h)&&!fd(a,h)&&(f[h]=b[h]);d.push(JSON.stringify(f));e.push("_default_");a=[];for(f=d.length-1;0<=f;f--)a[f]="?";return{ma:e,wa:a,za:d,
key:c}}
function Oc(a,b){if(!b)return"missing store: "+a.name;if(a.name!=b.name)return"store name, expect: "+a.name+", but: "+b.name;if(a.keyPath!=b.keyPath)return"keyPath, expect:  "+a.keyPath+", but: "+b.keyPath;if(v(a.autoIncrement)&&v(b.autoIncrement)&&a.autoIncrement!=b.autoIncrement)return"autoIncrement, expect:  "+a.autoIncrement+", but: "+b.autoIncrement;if(a.indexes.length!=b.indexes.length)return"indexes length, expect:  "+a.indexes.length+", but: "+b.indexes.length;if(v(a.type)&&v(b.type)&&a.type!=
b.type)return"data type, expect:  "+a.type+", but: "+b.type;for(var c=0;c<a.indexes.length;c++){var d=ed(b,a.indexes[c].name),d=!d?"no index for "+a.indexes[c].name:a.indexes[c].name!=d.name?"name, expect: "+a.indexes[c].name+", but: "+d.name:!gd(a.indexes[c].keyPath,d.keyPath)?"keyPath, expect: "+a.indexes[c].keyPath+", but: "+d.keyPath:a.indexes[c].unique!=d.unique?"unique, expect: "+a.indexes[c].unique+", but: "+d.unique:v(a.indexes[c].type)&&v(d.type)&&a.indexes[c].type!=d.type?"data type, expect: "+
a.indexes[c].type+", but: "+d.type:"";if(0<d.length)return'index "'+a.indexes[c].name+'" '+d}return""}function X(a,b){var c,d=b;if(z(a)){c=a.version;for(var d=[],e=a.stores||[],f=0;f<e.length;f++){var g=Nc(e[f]);d.push(g)}}else x(a)?c=0==a.length?l:parseFloat(a):y(a)&&(c=a);v(c)&&((!y(c)||0>c)&&j(new Q("Invalid version: "+c+" ("+a+")")),isNaN(c)&&(c=l));v(b)&&(!w(b)||0<b.length&&!(b[0]instanceof dd))&&j(new Q("stores"));this.version=c;this.b=!v(this.version);this.stores=d||[]}
X.prototype.toJSON=function(){var a=this.stores.map(function(a){return a.toJSON()});return{version:this.version,stores:a}};X.prototype.b=r;X.prototype.a=da(r);function Xb(a){return a.stores.map(function(a){return a.name})}X.prototype.d=function(a){return this.stores[a]||q};function T(a,b){return cb(a.stores,function(a){return a.name==b})}function Mc(a,b){return bb(a.stores,function(a){return a.name==b})}
function hd(a,b){if(!b||a.stores.length!=b.stores.length)return"Number of store: "+a.stores.length+" vs "+b.stores.length;for(var c=0;c<a.stores.length;c++){var d=T(b,a.stores[c].name),d=Oc(a.stores[c],d);if(0<d.length)return'store: "'+a.stores[c].name+'" '+d}return""};function id(a,b){v(a)&&5242880<a&&I(this.e,"storage size request ignored.");this.f=q;this.O=b||18E4}
id.prototype.u=function(a,b){function c(a,c,d){J(e.e,(d?"changing":"upgrading")+" version to "+a.version+" from "+(b.a()?"auto":b.version));for(d=0;d<b.stores.length;d++)jd(e,a,c,b.stores[d])}function d(a,b){v(b)?(I(e.e,b?b.message:"Error received."),e.f=q,H(f,b)):(e.f=a,e.f.onabort=function(a){K(e.e,e+": onabort - "+a.message)},e.f.onerror=function(a){K(e.e,e+": onerror - "+a.message)},e.f.onversionchange=function(a){K(e.e,e+": onversionchange to: "+a.version);e.f&&(e.f.onabort=q,e.f.onerror=q,e.f.onversionchange=
q,e.f.close(),e.f=q,ja(e.b)&&e.b())},G(f,m))}var e=this,f=new F,g=b.version;J(e.e,"Opening database: "+a+" ver: "+g);var h;h=v(g)?kd.open(a,g):kd.open(a);h.onsuccess=function(f){var g=f.target.result;J(e.e,"Database: "+g.name+", ver: "+g.version+" opened.");if(b.b)e.p(function(f){if(b.a())for(var h=0;h<f.stores.length;h++)if(!Mc(b,f.stores[h].name)){var n=Nc(f.stores[h].toJSON());b.stores.push(n)}f=hd(b,f);if(0<f.length){J(e.e,"Schema change require for difference in "+f);var p=y(g.version)?g.version+
1:1;if("IDBOpenDBRequest"in u){g.close();var P=kd.open(a,p);P.onupgradeneeded=function(a){a=a.target.result;J(e.e,"re-open for version "+a.version);c(a,P.transaction,r)};P.onsuccess=function(a){d(a.target.result)};P.onerror=function(){J(e.e,e+": fail.");d(q)}}else{var ea=g.setVersion(p+"");ea.a=function(a){I(e.e,"migrating from "+g.version+" to "+p+" failed.");d(q,a)};ea.onsuccess=function(){ea.transaction.oncomplete=Da;c(g,ea.transaction,m)};var Da=function(){var b=kd.open(a);b.onsuccess=function(a){a=
a.target.result;J(e.e,e+": OK.");d(a)};b.onerror=function(){J(e.e,e+": fail.");d(q)}};ea.transaction!=q&&(ea.transaction.oncomplete=Da)}}else d(g)},l,g);else if(b.version>g.version){var h=g.setVersion(b.version);h.a=function(a){I(e.e,"migrating from "+g.version+" to "+b.version+" failed.");d(q,a)};h.onsuccess=function(){c(g,h.transaction,m)}}else b.version==g.version?J(e.e,"database version "+g.version+" ready to go"):I(e.e,"connected database version "+g.version+" is higher than requested version."),
e.p(function(a){a=hd(b,a);0<a.length?(J(e.e,a),d(q,new Ub("different schema: "+a))):d(g)},l,g)};h.onupgradeneeded=function(a){a=a.target.result;J(e.e,"upgrade needed for version "+a.version);c(a,h.transaction,r)};h.onerror=function(c){Gb(e.e,"opening database "+a+":"+b.version+" failed.");d(q,c)};h.onblocked=function(c){Gb(e.e,"database "+a+" "+b.version+" block, close other connections.");d(q,c)};y(this.O)&&vc(function(){"done"!=h.readyState&&(Gb(e.e,e+": database state is still "+h.readyState),
d(q,Error("connection timeout after "+e.O)))},this.O);return f};var kd=u.indexedDB||u.mozIndexedDB||u.webkitIndexedDB||u.moz_indexedDB||u.msIndexedDB;s=id.prototype;s.O=18E4;s.type=da("indexeddb");s.ka=function(){return!!this.f};s.e=L("ydn.db.con.IndexedDb");s.f=q;
s.p=function(a,b,c){c=c||this.f;if(v(b)){if(b===q){if(0==c.objectStoreNames.length){a(new X(c.version));return}j(new Tb)}c=b.db}else{b=[];for(var d=c.objectStoreNames.length-1;0<=d;d--)b[d]=c.objectStoreNames[d];if(0==b.length){a(new X(c.version));return}b=c.transaction(b,U)}for(var e=c.objectStoreNames,f=[],g=e.length,d=0;d<g;d++){for(var h=b.objectStore(e[d]),n=[],k=0,p=h.indexNames.length;k<p;k++){var t=h.index(h.indexNames[k]);n[k]=new $c(t.keyPath,l,t.unique,t.multiEntry,t.name)}f[d]=new dd(h.name,
h.keyPath,h.autoIncrement,l,n)}b=new X(c.version,f);a(b)};
function jd(a,b,c,d){function e(){var a={autoIncrement:!!d.autoIncrement};d.keyPath!=q&&(a.keyPath=d.keyPath);try{return b.createObjectStore(d.name,a)}catch(c){j(c)}}K(a.e,"Creating Object Store for "+d.name+" keyPath: "+d.keyPath);if(b.objectStoreNames.contains(d.name)){c=c.objectStore(d.name);c.keyPath!=d.keyPath?(b.deleteObjectStore(d.name),I(a.e,"store: "+d.name+" deleted due to keyPath change."),c=e()):c.autoIncrement!=d.autoIncrement&&(b.deleteObjectStore(d.name),I(a.e,"store: "+d.name+" deleted due to autoIncrement change."),
c=e());for(var f=c.indexNames,g=0,h=0,n=0;n<d.indexes.length;n++){var k=d.indexes[n];f.contains(k.name)||(c.createIndex(k.name,k.keyPath,{unique:k.unique}),g++)}for(n=0;n<f.length;n++)fd(d,f[n])||(c.deleteIndex(f[n]),h++);K(a.e,"Updated store: "+c.name+", "+g+" index created, "+h+" index deleted.")}else{c=e();for(n=0;n<d.indexes.length;n++)k=d.indexes[n],K(a.e,"Creating index: "+k.name+" multiEntry: "+k.multiEntry),k.unique||k.multiEntry?c.createIndex(k.name,k.keyPath,{unique:k.unique,multiEntry:k.multiEntry}):
c.createIndex(k.name,k.keyPath);K(a.e,"Created store: "+c.name+" keyPath: "+c.keyPath)}}s.J=function(a,b,c,d){var e=this.f;if(!b){b=[];for(var f=e.objectStoreNames.length-1;0<=f;f--)b[f]=e.objectStoreNames[f]}0==b.length&&a(q);b=e.transaction(b,c);b.oncomplete=function(a){d("complete",a)};b.onerror=function(a){d("error",a)};b.onabort=function(a){d("abort",a)};a(b)};s.P=function(){this.f.close()};s.toString=function(){var a=this.f?this.f.name+":"+this.f.version:"";return this.type()+":"+a};function ld(){this.clear()}s=ld.prototype;s.setItem=function(a,b){v(this.a[a])||(this.keys.push(a.toString()),this.length=this.keys.length);this.a[a]=b};s.getItem=function(a){return this.a[a]||q};s.removeItem=function(a){delete this.a[a];eb(this.keys,a.toString());this.length=this.keys.length};s.length=0;s.key=function(a){a=this.keys[a];return v(a)?this.a[a]:q};s.clear=function(){this.a={};this.keys=[];this.length=0};function md(a){this.h=a||new ld}s=md.prototype;s.Aa=L("ydn.db.con.SimpleStorage");s.u=function(a,b){this.r=a;this.d=b;this.a={};for(var c=0;c<b.stores.length;c++){var d=b.d(c);this.a[d.name]=d.toJSON()}this.indexes={};d=nd(this);c=Vb(this.h.getItem(d));Xb(b);if(c)for(var e in c)c.hasOwnProperty(e)&&!Mc(b,e)&&(d=c[e],b.a()?(J(this.Aa,"Adding existing store: "+e),this.a[e]=d):(J(this.Aa,"Deleting old store: "+e),zc(this,e)));else this.h.setItem(d,JSON.stringify(this.a));return nb(m)};s.ka=function(){return!!this.r};
s.type=da("memory");s.P=ba();s.J=function(a,b,c,d){a(this);d("complete",{})};s.p=function(a){vc(function(){for(var b=[],c=this.h.getItem(nd(this)).stores,d=0;d<c.length;d++){var e=this.h.getItem(nd(this,c[d]));b[d]=new dd(c[d],e.keyPath,e.autoIncrement)}b=new X(this.r,b);a(b)},0,this)};function nd(a,b,c){a=["ydn.db",a.r];v(b)&&(a.push(b),v(c)&&a.push(Uc(c)));return a.join("^|")}function yc(a,b,c){b=nd(a,b instanceof dd?b.name:b,c);a=a.h.getItem(b);return a=a===q?l:Vb(a)}
function xc(a,b,c,d){var e;e=T(a.d,c);d=v(d)?d:e.keyPath!=q?ob(b,e.a):l;v(d)||(e.autoIncrement?(nd(a,e.name),d=a.a[e.name],v(d.autoIncrementNo)||(d.autoIncrementNo=Ac(a,e.name,q).length),d.autoIncrementNo++,d=d.autoIncrementNo):j(new Jb));e=d;d=nd(a,c,e);b=JSON.stringify(b);a.h.setItem(d,b);if(a=a.a[c].Keys){c=0;for(b=a.length;c<b&&e!=a[c];c++)if(e>a[c]){fb(a,c,0,e);break}}return e}
function zc(a,b,c){if(v(c))a.h.removeItem(nd(a,b,c)),a=a.a[b].Keys,v(a)&&eb(a,c);else if(v(b)){a.a[b]&&(a.a[b].Keys=q);c=nd(a,b)+"^|";for(b=a.h.length-1;0<=b;b--){var d=a.h.key(b);0==d.lastIndexOf(c,0)&&a.h.removeItem(d)}}else{c=nd(a)+"^|";for(b=a.h.length-1;0<=b;b--)d=a.h.key(b),0==d.lastIndexOf(c,0)&&a.h.removeItem(d)}}
s.index=function(a){var b=this.a[a],c=b.Keys;if(c==q){c=[];a=nd(this,a);a+="^|";for(var d=0,e=this.h.length;d<e;d++){var f=this.h.key(d);if(0==f.lastIndexOf(a,0)){c.push(f);for(var f=0,g=b.indexes.length;f<g;f++);}}E.sort.call(c,hb);b.Keys=c;b.indexes={}}return c};
function Ac(a,b,c){function d(){return function(a){return a>=l}}function e(){return function(a){return a<l}}c!=q&&j(new Sb);a=a.index(b);if(!v(l)&&!v(l))return a;if(v(l)){if(v(l))return b=db(a,e()),c=db(a,d()),a.slice(b,c);b=db(a,d());return a.slice(b)}b=db(a,e());return a.slice(0,b)};function od(){md.call(this,window.localStorage)}A(od,md);od.prototype.type=da("localstorage");function pd(){md.call(this,window.sessionStorage)}A(pd,md);pd.prototype.type=da("sessionstorage");function qd(a){this.a=v(a)?a:4194304}s=qd.prototype;
s.u=function(a,b){function c(a,b){v(b)?(d.n=q,H(e,b)):(d.n=a,G(e,m))}var d=this,e=new F,f=q;try{var g=b.b?"":b.version+"",f=u.openDatabase(a,"",a,this.a)}catch(h){"SECURITY_ERR"==h.name?(I(this.i,"SECURITY_ERR for opening "+a),f=q,this.ca=new Mb(h)):j(h)}if(f){f.version===g?K(this.i,"Existing database version "+f.version+" opened."):K(d.i,"Database version "+f.version+" opened, but require "+g+" version.");!b.b&&f.version<g&&K(d.i,"Upgrading to version: "+g);var n=f;K(d.i,a+": setting version from "+
n.version+" to "+b.version);var k=0;n.transaction(function(a){d.p(function(c){for(var e=0;e<b.stores.length;e++){var f=T(c,b.stores[e].name);rd(d,a,b.stores[e],function(){k++},f)}},a,n)},function(a){j(a)},function(){k!=b.stores.length?I(d.i,a+": setting version voided."):(K(d.i,a+": ready."),c(n))})}else c(q,this.ca);return e};s.type=da("websql");s.ca=q;s.n=q;s.i=L("ydn.db.con.WebSql");
s.p=function(a,b,c){function d(a,b){j(b)}function e(b,c){for(var d=0;d<c.rows.length;d++){var e=c.rows.item(d);if("__WebKitDatabaseInfoTable__"!=e.name&&"table"==e.type){for(var h=e.sql.substr(e.sql.indexOf("("),e.sql.lastIndexOf(")")).match(/(?:"[^"]*"|[^,])+/g),D="",Z,P=[],ea=r,Da=0;Da<h.length;Da++){var la=h[Da].match(/\w+|"[^"]+"/g),aa;a:{aa=la[0];for(var Ua=0;1>Ua;Ua++)if('"'==aa.charAt(0)&&'"'==aa.charAt(aa.length-1)){aa=aa.substring(1,aa.length-1);break a}}Ua=ad(la[1]);-1!=la.indexOf("PRIMARY")&&
-1!=la.indexOf("KEY")?(D=aa,Z=Ua,-1!=la.indexOf("AUTOINCREMENT")&&(ea=m)):"_default_"!=aa&&(la=new $c(aa,Ua,"UNIQUE"==la[2]),P.push(la))}e=new dd(e.name,D,ea,Z,P);g.push(e)}}d=new X(f,g);a(d)}var f=(c=c||this.n)&&c.version?parseInt(c.version,10):l,f=isNaN(f)?l:f,g=[];if(b)b.executeSql("SELECT * FROM sqlite_master",[],e,d);else{var h=this;c.readTransaction(function(b){h.p(a,b,c)},function(a){Gb(h.i,"opening tx: "+a.message);j(a)},e)}};
function rd(a,b,c,d,e){function f(a){b.executeSql(a,[],function(){D++;D==k.length&&d(m)},function(b,d){j(new Lb(d,"Error creating table: "+c.name+" "+a))})}var g="CREATE TABLE IF NOT EXISTS "+C(c.name)+" (",h=Ic(c)||"_ROWID_",n=c.type||"BLOB";"ARRAY"==n&&(n="TEXT");c.keyPath!=q?(g+=Ic(c)+" "+n+" UNIQUE PRIMARY KEY ",c.autoIncrement&&(g+=" AUTOINCREMENT ")):g=c.autoIncrement?g+("_ROWID_ "+n+" UNIQUE PRIMARY KEY AUTOINCREMENT "):g+("_ROWID_ "+n+" UNIQUE PRIMARY KEY ");for(var g=g+" ,_default_ BLOB",
k=[],n=0;n<c.indexes.length;n++){var p=c.indexes[n],t=p.unique?" UNIQUE ":" ",B="CREATE "+t+" INDEX IF NOT EXISTS "+C(p.name)+" ON "+C(c.name)+" ("+h+")";k.push(B);p.keyPath!=c.keyPath&&(g+=", "+C(p.keyPath)+" "+(p.type||"BLOB")+t)}k.unshift(g+");");var D=0,g="Create";if(e){if(0==Oc(c,e).length){K(a.i,c.name+" exists.");d(m);return}g="Modify"}K(a.i,g+" table: "+c.name+": "+k.join(";"));for(a=0;a<k.length;a++)f(k[a])}s.ka=function(){return!!this.n};s.P=ba();
s.J=function(a,b,c,d){function e(a){K(h.i,h+": Tx "+c+" request cause error.");d("error",a)}function f(){d("complete",{type:"complete"})}function g(b){a(b)}var h=this;this.n===q&&(a(q),d("error",this.ca));c==U?this.n.readTransaction(g,e,f):c==Sc?this.n.changeVersion(this.n.version,this.n.version+1+"",g,e,f):this.n.transaction(g,e,f)};function sd(a,b){R.call(this,a,b)}A(sd,R);function td(a,b,c,d){R.call(this,a,b);this.message=d||""}A(td,sd);td.prototype.message="";function ud(a,b){X.call(this,a,b)}A(ud,X);ud.prototype.a=da(m);function gd(a,b){var c;c=c||{};if(a==q||b==q)return r;if(w(a)&&w(b)){if(a.length!=b.length)return r;for(var d=0;d<a.length;d++)if(-1==cb(b,function(b){return gd(b,a[d])}))return r;return m}if(w(a))return 1==a.length&&gd(a[0],b);if(w(b))return 1==b.length&&gd(b[0],a);if(z(a)&&z(a)){for(var e in a)if(a.hasOwnProperty(e)&&!c[e]){var f=gd(a[e],b[e]);if(!f)return r}for(e in b)if(b.hasOwnProperty(e)&&!c[e]&&(f=gd(a[e],b[e]),!f))return r;return m}return a===b};/*
 Copyright 2012 YDN Authors, Yathit. All Rights Reserved.
*/
function Y(a,b,c){$b.call(this);c=c||{};this.Fa=c.mechanisms||vd;this.pa=c.size;this.ya=v(c.ya)?c.ya:r;this.b=q;this.j=[];this.M=r;this.a=b instanceof X?b:z(b)?c.autoSchema||!v(b.stores)?new ud(b):new X(b):new ud;v(a)&&this.ua(a)}A(Y,tc);s=Y.prototype;s.Q=L("ydn.db.con.Storage");s.Ja=function(a){if(v(a)){var b=function(b){a(b.toJSON())};if(this.b)this.b.p(b);else{var c=this;this.v(function(a){c.b.p(b,a)},q,U)}}return this.a?this.a.toJSON():q};
s.Y=function(a){var b=a instanceof dd?a:Nc(a);a=a.name;var c=T(this.a,a);if(0==Oc(b,c).length)return nb(r);c=c?"update":"add";if(this.a instanceof ud)return this.a.stores.push(b),this.b?(this.b.P(),this.b=q,wd(this)):nb(r);j(new Ub("Cannot "+c+" store: "+a+". Not auto schema generation mode."))};s.ua=function(a){this.b&&j(Error("Already defined."));this.d=a;wd(this)};s.w=ca("d");var vd=["indexeddb","websql","localstorage","sessionstorage","memory"];
function xd(a,b){return"indexeddb"==b?new id(a.pa):"websql"==b?new qd(a.pa):"localstorage"==b?new od:"sessionstorage"==b?new pd:"memory"==b?new md:q}
function wd(a){for(var b=new F,c=q,d=a.Fa,e=0;e<d.length;e++){var f=d[e].toLowerCase();if("indexeddb"==f&&kd){c=xd(a,f);break}else if("websql"==f&&ja(u.openDatabase)){c=xd(a,f);break}else if("localstorage"==f&&window.localStorage){c=xd(a,f);break}else if("sessionstorage"==f&&window.sessionStorage){c=xd(a,f);break}else if("memory"==f){c=xd(a,f);break}}c===q&&j(new Ub("No storage mechanism found."));c.u(a.d,a.a).W(function(){a.b=c;K(a.Q,a+": ready.");a.Ka=NaN;nb(m);yd(a);sc(a,new td("connected",a));
c.b=function(){K(a.Q,a+": disconnected.")}}).X(function(b){I(a.Q,a+": opening fail: "+b.message);H(new F,b);if(a.j){a.Q.log(Bb,"Purging "+a.j.length+" transactions request.",l);for(var c=a.j.shift();c;)c.o("error",b),c=a.j.shift()}sc(a,new td("failed",a,0,"opening database fail: "+b.message))});return b}s=Y.prototype;s.type=function(){return this.b?this.b.type():""};s.la=function(){this.b&&(this.b.P(),this.b=q)};s.Ka=NaN;
function yd(a){var b=a.j.shift();b&&Y.prototype.v.call(a,b.aa,b.Ga,b.mode,b.o);ra()}s.M=r;s.v=function(a,b,c,d){var e=b;x(b)?e=[b]:b!=q?(!w(b)||!x(b[0]))&&j(new Q("storeNames")):e=q;if(!this.b||!this.b.ka()||this.M)this.j.push({aa:a,Ga:e,mode:c,o:d}),ra();else{var f=this,g=v(c)?c:U;g==Sc&&(this.M=m);this.b.J(function(b){a(b)},e,g,function(a,b){ja(d)&&d(a,b);g==Sc&&(f.M=r);yd(f)})}};s.toString=function(){return"ydn.db.con.Storage:"+this.b};function Kc(){this.a=q}Kc.prototype.b=L("ydn.db.tr.Mutex");Kc.prototype.o=q;Kc.prototype.toString=da("Mutex");function zd(a,b,c){Y.call(this,a,b,c);this.K=0}A(zd,Y);zd.prototype.K=0;zd.prototype.ha=function(){return new Jc(this,this.K++)};zd.prototype.H=function(a,b,c,d,e){var f=this.ha(a.name||"");if(4<arguments.length){var g=Array.prototype.slice.call(arguments,4),h=function(){var b=Array.prototype.slice.call(arguments),b=b.concat(g);return a.apply(this,b)};h.name=a.name;f.H(h,b,c,d)}else f.H(a,b,c,d)};function $(a,b,c){zd.call(this,a,b,c);this.g=this.ha("base")}A($,zd);s=$.prototype;s.ha=function(){return new V(this,this.K++,0,this.a)};s.R=function(a,b,c){return this.g.R(a,b,c)};s.S=function(a,b){return this.g.S(a,b)};s.keys=function(a,b,c,d,e,f,g){return this.g.keys(a,b,c,d,e,f,g)};s.T=function(a,b,c,d,e,f,g){return this.g.T(a,b,c,d,e,f,g)};s.U=function(a,b,c){return this.g.U(a,b,c)};s.clear=function(a,b){return this.g.clear(a,b)};s.toString=function(){return"Storage:"+this.w()};sa("ydn.db.core.Storage",$);$.prototype.get=$.prototype.S;$.prototype.list=$.prototype.T;$.prototype.put=$.prototype.U;$.prototype.clear=$.prototype.clear;$.prototype.count=$.prototype.R;V.prototype.get=V.prototype.S;V.prototype.list=V.prototype.T;V.prototype.put=V.prototype.U;V.prototype.clear=V.prototype.clear;V.prototype.count=V.prototype.R;sa("ydn.db.cmp",function(a,b){if(kd)return kd.cmp(a,b);a=Uc(a);b=Uc(b);return a>b?1:a==b?0:-1});sa("ydn.db.Key",N);N.prototype.id=N.prototype.Da;
N.prototype.parent=N.prototype.Ia;N.prototype.storeName=N.prototype.Ea;sa("ydn.db.KeyRange",O);O.upperBound=function(a,b){return new O(l,a,l,b)};O.lowerBound=function(a,b){return new O(a,l,b,l)};O.bound=Ob;O.only=function(a){return new O(a,a,r,r)};O.starts=function(a){var b;w(a)?(b=Vb(JSON.stringify(a)),b.push("\uffff")):x(a)?b=a+"\uffff":j(new Q);return Ob(a,b,r,m)};F.prototype.done=F.prototype.W;F.prototype.fail=F.prototype.X;F.prototype.then=F.prototype.z;tc.prototype.addEventListener=tc.prototype.addEventListener;sa("ydn.db.con.Storage",Y);Y.prototype.type=Y.prototype.type;Y.prototype.setName=Y.prototype.ua;Y.prototype.getSchema=Y.prototype.Ja;Y.prototype.transaction=Y.prototype.v;Y.prototype.close=Y.prototype.la;
sa("ydn.db.deleteDatabase",function(a){function b(){c.i.log(Bb,"all tables in "+a+" deleted.",l)}kd&&"deleteDatabase"in kd&&kd.deleteDatabase(a);var c=new qd,d=new ud,d=c.u(a,d);d.W(function(){c.J(function(b){c.p(function(d){var e=d.stores.length;if(0<e)for(var n=0;n<e;n++){var k=d.d(n);J(c.i,"deleting table: "+k.name);b.executeSql("DROP TABLE "+C(k.name))}else c.i.log(Bb,"no table to delete in "+a,l)},b)},[],Pc,b)});d.X(function(){I(c.i,"Connecting "+a+" failed.")});var d=new od,e=new ud;d.u(a,e);
zc(d);d=new pd;e=new ud;d.u(a,e);zc(d)});})();
