(function(){function j(a){throw a;}var k=void 0,n=!0,p=null,r=!1;function aa(){return function(){}}function s(a){return function(){return this[a]}}function ba(a){return function(){return a}}var u,v=this;function ca(a){a=a.split(".");for(var b=v,c;c=a.shift();)if(b[c]!=p)b=b[c];else return p;return b}
function fa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function w(a){return a!==k}function x(a){return"array"==fa(a)}function ga(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function y(a){return"string"==typeof a}function ha(a){return"boolean"==typeof a}function z(a){return"number"==typeof a}function ia(a){return"function"==fa(a)}function B(a){var b=typeof a;return"object"==b&&a!=p||"function"==b}function ja(a){return a[ka]||(a[ka]=++ma)}
var ka="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ma=0;function na(a,b,c){return a.call.apply(a.bind,arguments)}function oa(a,b,c){a||j(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}
function pa(a,b,c){pa=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?na:oa;return pa.apply(p,arguments)}function qa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}var ra=Date.now||function(){return+new Date};
function C(a,b){var c=a.split("."),d=v;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&w(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function D(a,b){function c(){}c.prototype=b.prototype;a.M=b.prototype;a.prototype=new c};function sa(a){if(!ta.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ua,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(va,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(wa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(xa,"&quot;"));return a}var ua=/&/g,va=/</g,wa=/>/g,xa=/\"/g,ta=/[&<>\"]/;function za(a,b){for(var c=b.length,d=0;d<c;d++){var e=1==c?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a}
var Aa={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"},Ba={"'":"\\'"};
function E(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=b,g=c+1,h;if(!(h=Aa[d])){if(!(31<e&&127>e))if(d in Ba)d=Ba[d];else if(d in Aa)d=Ba[d]=Aa[d];else{e=d;h=d.charCodeAt(0);if(31<h&&127>h)e=d;else{if(256>h){if(e="\\x",16>h||256<h)e+="0"}else e="\\u",4096>h&&(e+="0");e+=h.toString(16).toUpperCase()}d=Ba[d]=e}h=d}f[g]=h}b.push('"');return b.join("")};var Ca,Da,Ea,Fa;function Ga(){return v.navigator?v.navigator.userAgent:p}Fa=Ea=Da=Ca=r;var Ha;if(Ha=Ga()){var Ja=v.navigator;Ca=0==Ha.indexOf("Opera");Da=!Ca&&-1!=Ha.indexOf("MSIE");Ea=!Ca&&-1!=Ha.indexOf("WebKit");Fa=!Ca&&!Ea&&"Gecko"==Ja.product}var Ka=Ca,La=Da,Ma=Fa,Na=Ea,Oa;
a:{var Pa="",Qa;if(Ka&&v.opera)var Ra=v.opera.version,Pa="function"==typeof Ra?Ra():Ra;else if(Ma?Qa=/rv\:([^\);]+)(\)|;)/:La?Qa=/MSIE\s+([^\);]+)(\)|;)/:Na&&(Qa=/WebKit\/(\S+)/),Qa)var Sa=Qa.exec(Ga()),Pa=Sa?Sa[1]:"";if(La){var Ta,Ua=v.document;Ta=Ua?Ua.documentMode:k;if(Ta>parseFloat(Pa)){Oa=String(Ta);break a}}Oa=Pa}var Va={};
function Wa(a){var b;if(!(b=Va[a])){b=0;for(var c=String(Oa).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",m=/(\d*)(\D*)/g,l=/(\d*)(\D*)/g;do{var q=m.exec(g)||["","",""],t=l.exec(h)||["","",""];if(0==q[0].length&&0==t[0].length)break;b=((0==q[1].length?0:parseInt(q[1],10))<(0==t[1].length?0:parseInt(t[1],10))?-1:(0==q[1].length?0:parseInt(q[1],10))>(0==t[1].length?
0:parseInt(t[1],10))?1:0)||((0==q[2].length)<(0==t[2].length)?-1:(0==q[2].length)>(0==t[2].length)?1:0)||(q[2]<t[2]?-1:q[2]>t[2]?1:0)}while(0==b)}b=Va[a]=0<=b}return b}var Xa={};function Ya(){return Xa[9]||(Xa[9]=La&&!!document.documentMode&&9<=document.documentMode)};function Za(a){Error.captureStackTrace?Error.captureStackTrace(this,Za):this.stack=Error().stack||"";a&&(this.message=String(a))}D(Za,Error);Za.prototype.name="CustomError";var $a=Array.prototype,ab=$a.indexOf?function(a,b,c){return $a.indexOf.call(a,b,c)}:function(a,b,c){c=c==p?0:0>c?Math.max(0,a.length+c):c;if(y(a))return!y(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},bb=$a.map?function(a,b,c){return $a.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=y(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},cb=$a.some?function(a,b,c){return $a.some.call(a,b,c)}:function(a,b,c){for(var d=
a.length,e=y(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return n;return r};function db(a,b){var c=eb(a,b,k);return 0>c?p:y(a)?a.charAt(c):a[c]}function eb(a,b,c){for(var d=a.length,e=y(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1}function fb(a){if(!x(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0}function gb(a,b){var c=ab(a,b);0<=c&&$a.splice.call(a,c,1)}
function hb(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function ib(a,b,c,d){$a.splice.apply(a,jb(arguments,1))}function jb(a,b,c){return 2>=arguments.length?$a.slice.call(a,b):$a.slice.call(a,b,c)}function kb(a,b){return a>b?1:a<b?-1:0};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function G(a,b){this.a=[];this.h=b||p}u=G.prototype;u.ra=r;u.sa=r;u.Ba=0;u.Ob=r;u.bc=r;u.ac=0;u.Ab=function(a,b){lb(this,a,b);this.Ba--;0==this.Ba&&this.ra&&ob(this)};function lb(a,b,c){a.ra=n;a.b=c;a.sa=!b;ob(a)}function pb(a){a.ra&&(a.Ob||j(new qb),a.Ob=r)}function H(a,b){pb(a);lb(a,n,b)}function I(a,b){pb(a);lb(a,r,b)}u.Ia=function(a,b){return this.R(a,p,b)};u.Ja=function(a,b){return this.R(p,a,b)};u.R=function(a,b,c){this.a.push([a,b,c]);this.ra&&ob(this);return this};
function rb(a){return cb(a.a,function(a){return ia(a[1])})}function ob(a){a.c&&(a.ra&&rb(a))&&(v.clearTimeout(a.c),delete a.c);a.d&&(a.d.ac--,delete a.d);for(var b=a.b,c=r,d=r;a.a.length&&0==a.Ba;){var e=a.a.shift(),f=e[0],g=e[1],e=e[2];if(f=a.sa?g:f)try{var h=f.call(e||a.h,b);w(h)&&(a.sa=a.sa&&(h==b||h instanceof Error),a.b=b=h);b instanceof G&&(d=n,a.Ba++)}catch(m){b=m,a.sa=n,rb(a)||(c=n)}}a.b=b;d&&a.Ba&&(b.R(pa(a.Ab,a,n),pa(a.Ab,a,r)),b.bc=n);c&&(a.c=v.setTimeout(function(){j(b)},0))}
function sb(a){var b=new G;H(b,a);return b}function qb(){Za.call(this)}D(qb,Za);qb.prototype.message="Deferred has already fired";qb.prototype.name="AlreadyCalledError";function tb(a,b){for(var c=ga(b),d=c?b:arguments,c=c?0:1;c<d.length&&!(a=a[d[c]],!w(a));c++);return a}var ub="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function vb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ub.length;f++)c=ub[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function wb(a){return xb(a||arguments.callee.caller,[])}
function xb(a,b){var c=[];if(0<=ab(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(yb(a)+"(");for(var d=a.arguments,e=0;e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=yb(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(xb(a.caller,b))}catch(g){c.push("[exception trying to get caller]\n")}}else a?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function yb(a){if(zb[a])return zb[a];a=String(a);if(!zb[a]){var b=/function ([^\(]+)/.exec(a);zb[a]=b?b[1]:"[Anonymous]"}return zb[a]}var zb={};function Ab(a,b,c,d,e){"number"==typeof e||Bb++;d||ra();this.c=b;delete this.b;delete this.a}Ab.prototype.b=p;Ab.prototype.a=p;var Bb=0;function Cb(){}Cb.prototype.a=p;Cb.prototype.c=p;Cb.prototype.b=p;function Db(a,b){this.name=a;this.value=b}Db.prototype.toString=s("name");var Eb=new Db("SEVERE",1E3),Fb=new Db("WARNING",900),Gb=new Db("INFO",800),Hb=new Db("CONFIG",700),Ib=new Db("FINER",400),Jb=new Db("FINEST",300);function Kb(a){return a.c?a.c:a.a?Kb(a.a):p}
Cb.prototype.log=function(a,b,c){if(a.value>=Kb(this).value){a="log:"+this.d(a,b,c).c;v.console&&(v.console.timeStamp?v.console.timeStamp(a):v.console.markTimeline&&v.console.markTimeline(a));v.msWriteProfilerMark&&v.msWriteProfilerMark(a);for(a=this;a;)a=a.a}};
Cb.prototype.d=function(a,b,c){var d=new Ab(0,String(b));if(c){d.b=c;var e;var f=arguments.callee.caller;try{var g;var h=ca("window.location.href");if(y(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:h,stack:"Not available"};else{var m,l,q=r;try{m=c.lineNumber||c.zc||"Not available"}catch(t){m="Not available",q=n}try{l=c.fileName||c.filename||c.sourceURL||h}catch(A){l="Not available",q=n}g=q||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:m,
fileName:l,stack:c.stack||"Not available"}:c}e="Message: "+sa(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+sa(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+sa(wb(f)+"-> ")}catch(F){e="Exception trying to expose exception! You win, we lose. "+F}d.a=e}return d};function Lb(a,b){a.log(Eb,b,k)}function J(a,b){a.log(Fb,b,k)}function K(a,b){a.log(Ib,b,k)}function L(a,b){a.log(Jb,b,k)}var Mb={},Nb=p;
function M(a){Nb||(Nb=new Cb,Mb[""]=Nb,Nb.c=Hb);var b;if(!(b=Mb[a])){b=new Cb;var c=a.lastIndexOf("."),d=a.substr(c+1),c=M(a.substr(0,c));c.b||(c.b={});c.b[d]=b;b.a=c;Mb[a]=b}return b};M("ydn");function Ob(a){if(!y(a)||/^[\s\xa0]*$/.test(a))return{};try{return JSON.parse(a)}catch(b){j(b)}};function Pb(a,b){var c;c=c||{};if(a==p||b==p)return r;if(x(a)&&x(b)){if(a.length!=b.length)return r;for(var d=0;d<a.length;d++)if(-1==db(b,function(b){return Pb(b,a[d])}))return r;return n}if(x(a))return 1==a.length&&Pb(a[0],b);if(x(b))return 1==b.length&&Pb(b[0],a);if(B(a)&&B(a)){for(var e in a)if(a.hasOwnProperty(e)&&!c[e]){var f=Pb(a[e],b[e]);if(!f)return r}for(e in b)if(b.hasOwnProperty(e)&&!c[e]&&(f=Pb(a[e],b[e]),!f))return r;return n}return a===b}
function Qb(a){for(var b in a)if(a.hasOwnProperty(b))return a[b]};function O(a,b,c,d){this.lower=a;this.upper=b;this.lowerOpen=!!c;this.upperOpen=!!d}u=O.prototype;u.lower=k;u.upper=k;u.lowerOpen=r;u.upperOpen=r;u.toJSON=function(){return Rb(this)};function Sb(a,b,c,d){return new O(a,b,c,d)}function Rb(a){a=a||{};return{lower:a.lower,upper:a.upper,lowerOpen:a.lowerOpen,upperOpen:a.upperOpen}}
function Tb(a){return a==p?p:w(a.upper)&&w(a.lower)?Ub.bound(a.lower,a.upper,!!a.lowerOpen,!!a.upperOpen):w(a.upper)?Ub.upperBound(a.upper,a.upperOpen):w(a.lower)?Ub.lowerBound(a.lower,a.lowerOpen):p}var Ub=v.IDBKeyRange||v.webkitIDBKeyRange||O;function Vb(a,b,c,d,e){var f,g,h,m;if(B(b))g=b.lower,f=b.upper,m=b.lowerOpen,h=b.upperOpen;else{if("<"==b||"<="==b)f=c,h="<"==b;else if(">"==b||">="==b)g=c,m=">"==b;else if("="==b||"=="==b)f=g=c;"<"==d||"<="==d?(f=e,h="<"==d):">"==d||">="==d?(g=e,m=">"==d):w(d)&&j(new P(d))}O.call(this,g,f,m,h);this.X=a}D(Vb,O);Vb.prototype.X="";
function Wb(a,b){var c="",d=[];if(b){var e=E(a);Xb(b)?(c=e+" LIKE ?",d.push(b.lower+"%")):b.lower==b.upper?(c=e+" = ?",d.push(b.lower)):(w(b.lower)&&(c+=" "+e+(b.lowerOpen?" > ":" >= ")+"?",d.push(b.lower)),w(b.upper)&&(c+=(0<c.length?" AND ":" ")+e+(b.upperOpen?" < ":" <= ")+"?",d.push(b.upper)))}return{sql:c,ob:d}}function Xb(a){return a==p?r:w(a.lower)&&w(a.upper)&&!a.lowerOpen&&!a.upperOpen&&a.lower.length==a.upper.length+1&&"\uffff"==a.upper[a.lower.length-1]};var Yb={READ_ONLY:"readonly",READ_WRITE:"readwrite",VERSION_CHANGE:"versionchange"},Zb=v.webkitIDBRequest&&"LOADING"in v.webkitIDBRequest?v.webkitIDBTransaction||v.IDBTransaction:Yb,R=Zb.READ_ONLY,$b=Zb.READ_WRITE,ac=Zb.VERSION_CHANGE;function bc(a,b){return a?b?"prevunique":"prev":b?"nextunique":"next"};function P(a){Error.captureStackTrace?Error.captureStackTrace(this,P):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.ArgumentException"}D(P,Error);function dc(a){Error.captureStackTrace?Error.captureStackTrace(this,dc):this.stack=Error().stack||"";a&&(this.message=String(a))}D(P,Error);dc.prototype.name="ydn.NotSupportedException";
function ec(a){Error.captureStackTrace?Error.captureStackTrace(this,ec):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.NotImplementedException"}D(ec,Error);function fc(a){Error.captureStackTrace?Error.captureStackTrace(this,fc):this.stack=Error().stack||"";a&&(this.message=String(a))}D(fc,Error);fc.prototype.name="ydn.InternalError";
function gc(a){Error.captureStackTrace?Error.captureStackTrace(this,gc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.ConstrainError"}D(gc,Error);function hc(a){Error.captureStackTrace?Error.captureStackTrace(this,hc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.InvalidOperationException"}D(P,Error);
function ic(a){Error.captureStackTrace?Error.captureStackTrace(this,ic):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.InvalidOperationError"}D(ic,Error);function S(a,b,c,d,e,f){y(a)||j(new P("store"));var g;x(b)?g=b.join(", "):y(b)?g=b:(w(b)&&j(new P("index")),g=k);6<arguments.length&&j(new P("too many input arguments."));this.B=a;this.index=g;this.w=w(f)?f:!!y(this.index);ha(this.w)||j(new P("key_only"));w(d)&&!ha(d)&&j(new P("reverse"));w(e)&&!ha(e)&&j(new P("unique"));g="next";d&&e?g="prevunique":d?g="prev":e&&(g="nextunique");this.direction=g;this.c=Tb(c);this.Na=[];this.Cb=[];this.Db=[];this.fb=[];this.eb=[];this.d=0;this.t=this.b=this.a=k;this.va=
r}function jc(a,b,c,d,e){B(b)&&!x(b)&&(e=d,d=w(c)?c:k,c=b,b=k);S.call(this,a,b,c,d,e,n)}D(jc,S);function kc(a,b,c,d,e){B(b)&&!x(b)&&(e=d,d=w(c)?c:k,c=b,b=k);S.call(this,a,b,c,d,e,r)}D(kc,S);u=S.prototype;u.Tb=M("ydn.db.Iterator");u.nc=s("B");u.mc=s("index");u.t=k;u.va=r;u.K=s("a");u.ec=function(){return Tb(this.c)};u.w=n;u.pc=s("w");u.toJSON=function(){return{store:this.B,index:this.index,key_range:this.c?Rb(this.c):p,direction:this.direction}};
u.toString=function(){return"Iterator:"+this.B+(w(this.index)?":"+this.index:"")};u.key=s("a");u.oc=s("b");u.ic=function(a,b){this.a=a;this.b=b};u.lc=s("d");u.cc=s("t");u.stores=function(){return[this.B].concat(this.Ua)};u.Ua=[];u.gc=[];u.$b=[];u.Sb=function(){return"prev"===this.direction||"prevunique"===this.direction};u.fc=function(){return"nextunique"===this.direction||"prevunique"===this.direction};u.Na=[];u.Cb=[];u.Db=[];u.fb=[];u.eb=[];
function lc(a){a.a=x(a.a)?hb(a.a):a.a;a.b=x(a.b)?hb(a.b):a.b;a.va=r;a.t=r;L(a.Tb,a+": exited")}
function mc(a,b){var c;if(0<a.Na.length){var d,e;a.t===r?(d=a.a,e=a.b):a.d=0;a.va=n;var f=[],g=b.Pa(a.B,a.index,a.c,a.direction,a.w,d,e);g.r=function(b,c){w(b)?(a.t=r,a.a=b,a.b=c,m()&&l()):(a.t=n,a.va=r)};c=function(b,c,d){m();w(c)&&(a.fb[b]=c,a.eb[b]=d);m()&&l()};for(var h=0;h<a.Na.length;h++)d=b.Pa(a.Db[h]||a.B,a.Na[h],a.Cb[h],a.direction,n,a.fb[h],a.eb[h]),f.push(d),d.r=qa(c,h);var m=function(){return!f.some(function(a){return a.jb})},l=function(){for(var b=r,c=n,d=[],e=a.a,h=0;h<f.length;h++){var m=
f[h];if(m.ta()){var l=nc(a.a,m.K());d[h]=l;1===l?c=r:-1===l&&(c=r,b=n,1===nc(m.K(),e)&&(e=m.K()))}else c=r}if(c){g.q(g.K(),g.xb(),g.hb());for(h=0;h<f.length;h++)f[h].forward(n)}else if(b){e!=a.a&&g.seek(e,k,n);for(h=0;h<f.length;h++)0==d[h]?f[h].seek(e):-1==d[h]?f[h].seek(e):f[h].ta()?e!=f[h].K()&&f[h].seek(e):f[h].seek(e)}else{a.a!=e&&g.seek(e);for(h=0;h<f.length;h++)(!f[h].ta()||0!==nc(f[h].K(),e))&&f[h].seek(e)}};c=g}else{(d=a.t===r)?(c=a.a,h=a.b):a.d=0;a.t=k;var q=b.Pa(a.B,a.index,a.c,a.direction,
a.w,c,h);L(a.Tb,a+" created "+q);q.r=function(b,c,d){w(b)?(a.a=b,a.b=c,a.d++,q.q(b,c,d)):(a.t=n,q.q(k,k,k))};q.u(c,h,d);c=q}return c}u.qc=function(){"working"==(w(this.t)?this.t===r?this.va?"working":"resting":"completed":"initial")&&j(new ic("working"));this.d=0;this.t=this.b=this.a=k};function oc(a){Error.captureStackTrace?Error.captureStackTrace(this,oc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.db.InvalidKeyException"}D(oc,Error);function pc(a){Error.captureStackTrace?Error.captureStackTrace(this,pc):this.stack=Error().stack||"";a&&(this.message=String(a))}D(pc,Error);pc.prototype.name="ydn.db.InternalError";
function qc(a){Error.captureStackTrace?Error.captureStackTrace(this,qc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="InvalidStateError"}D(qc,Error);function rc(a){Error.captureStackTrace?Error.captureStackTrace(this,rc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="InvalidAccessError"}D(rc,Error);function T(a){Error.captureStackTrace?Error.captureStackTrace(this,T):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="NotFoundError"}D(T,Error);
T.prototype.name="NotFoundError";function sc(a,b){Error.captureStackTrace?Error.captureStackTrace(this,sc):this.stack=Error().stack||"";b&&(this.message=String(b));this.message+=" :"+a.message+" ["+a.code+"]";this.name="SQLError"}D(sc,Error);function tc(a,b){Error.captureStackTrace?Error.captureStackTrace(this,tc):this.stack=Error().stack||"";b&&(this.message=String(b));this.message+=" :"+a.message;this.name="SecurityError"}D(tc,Error);
function uc(a){Error.captureStackTrace?Error.captureStackTrace(this,uc):this.stack=Error().stack||"";a&&(this.message=String(a));this.name="ydn.db.SqlParseError"}D(uc,Error);function vc(a,b,c){var d;B(a)?(d=a.store,b=a.id,a.parent!=p&&(c=new vc(a.parent))):w(b)?d=a:(d=a.lastIndexOf("^|"),b=a,0<d&&(b=a.substr(d),c=new vc(a.substring(0,d))),b=b.split("^:"),d=b[0],b=b[1],w(b)||j(Error("Invalid key value: "+a)));this.a=d;this.id=b;this.b=c||p}u=vc.prototype;u.toJSON=function(){var a={store:this.a,id:this.id};this.b&&(a.parent=this.b.toJSON());return a};u.valueOf=function(){return(this.b?this.b.valueOf()+"^|":"")+this.a+"^:"+this.id};
u.toString=function(){return this.valueOf().replace("^|","|").replace("^:",":")};u.sc=s("a");u.dc=s("id");u.rc=s("b");function wc(a,b){this.ga=a;this.a=b}wc.prototype.n=M("ydn.db.req.RequestExecutor");wc.prototype.e=p;function xc(a,b){wc.call(this,a,b)}D(xc,wc);u=xc.prototype;u.n=M("ydn.db.core.req.IndexedDb");u.i=s("e");u.La=function(a,b){function c(f){var g=d.e.objectStore(b[f]).count();g.onsuccess=function(d){e[f]=d.target.result;f++;f==b.length?H(a,e):c(f)};g.onerror=function(b){I(a,b)}}var d=this,e=[];0==b.length?H(a,[]):c(0)};u.pb=function(a,b,c,d){b=this.e.objectStore(b);var e;try{e=w(d)?b.put(c,d):b.put(c)}catch(f){j(f)}e.onsuccess=function(b){H(a,b.target.result)};e.onerror=function(b){I(a,b)}};
u.qb=function(a,b,c,d){function e(b){var l;try{l=w(d)?h.put(c[b],d[b]):h.put(c[b])}catch(q){j(q)}l.onsuccess=function(d){g++;f[b]=d.target.result;g==c.length?H(a,f):(d=b+10,d<c.length&&e(d))};l.onerror=function(b){g++;I(a,b)}}var f=[],g=0,h=this.e.objectStore(b);if(0<c.length)for(b=0;10>b&&b<c.length;b++)e(b);else H(a,[])};
u.bb=function(a,b,c){b=this.e.objectStore(b).openCursor(c);b.onsuccess=function(b){var c=b.target.result;c?(c=c["delete"](),c.onsuccess=function(){H(a,n)},c.onerror=function(){I(a,b)}):H(a,r)};b.onerror=function(b){I(a,b)}};u.pa=function(a,b){for(var c=x(b)&&0<b.length?b:y(b)?[b]:yc(this.a),d=c.length,e=0,f=0;f<d;f++){var g=this.e.objectStore(c[f]).clear();g.onsuccess=function(){e++;e==d&&H(a,n)};g.onerror=function(b){e++;e==d&&I(a,b)}}};
function zc(a,b,c,d,e,f,g,h,m){var l=[];a=a.e.objectStore(c);f=bc(f,m);d=d?a.index(d).openCursor(e,f):a.openCursor(e,f);var q=r;d.onsuccess=function(a){(a=a.target.result)?!q&&0<h?(q=n,a.advance(h)):(l.push(a.value),l.length<g?a.advance(1):H(b,l)):H(b,l)};d.onerror=function(a){I(b,a)}}u.ya=function(a,b,c,d,e,f){zc(this,a,b,p,c,d,e,f)};u.Sa=function(a,b,c,d,e,f,g,h){zc(this,a,b,c,d,e,f,g,h)};
u.Ib=function(a,b,c,d,e,f){var g=[];b=this.e.objectStore(b).openCursor(c,bc(d));var h=r;b.onsuccess=function(b){(b=b.target.result)?!h&&0<f?(h=n,b.advance(f)):(g.push(b.key),g.length<e?b.advance(1):H(a,g)):H(a,g)};b.onerror=function(b){I(a,b)}};u.Jb=function(a,b,c,d,e){var f=[];b=this.e.objectStore(b).openCursor(p,bc(c));var g=r;b.onsuccess=function(b){(b=b.target.result)?!g&&0<e?(g=n,b.advance(e)):(f.push(b.primaryKey),f.length<d?b.advance(1):H(a,f)):H(a,f)};b.onerror=function(b){I(a,b)}};
u.Gb=function(a,b,c,d,e,f,g,h){var m=[];b=this.e.objectStore(b).index(c).openKeyCursor(d,bc(e,h));var l=r;b.onsuccess=function(b){(b=b.target.result)?!l&&0<g?(l=n,b.advance(g)):(m.push(b.primaryKey),m.length<f&&b.advance(1)):H(a,m)};b.onerror=function(b){I(a,b)}};u.Oa=function(a,b,c){var d;try{d=this.e.objectStore(b)}catch(e){"NotFoundError"==e.name&&j(new T(b+" not in Tx scope: ?")),j(e)}b=d.get(c);b.onsuccess=function(b){H(a,b.target.result)};b.onerror=function(b){I(a,b)}};
u.lb=function(a,b,c){function d(b){if(c[b]==p)if(f++,e[b]=k,f==h)H(a,e);else{var l=b+10;l<h&&d(l)}var q;try{q=g.get(c[b])}catch(t){"DataError"==t.name&&j(new oc(c[b])),j(t)}q.onsuccess=function(c){f++;e[b]=c.target.result;f==h?H(a,e):(c=b+10,c<h&&d(c))};q.onerror=function(b){f++;I(a,b)}}var e=[],f=0,g=this.e.objectStore(b),h=c.length;if(0<h)for(b=0;10>b&&b<h;b++)d(b);else H(a,[])};
u.mb=function(a,b){function c(g){var m=b[g],l=d.e.objectStore(m.a),q;try{q=l.get(m.id)}catch(t){"DataError"==t.name&&j(new oc(m+" at "+g)),j(t)}q.onsuccess=function(d){f++;e[g]=d.target.result;f==b.length?H(a,e):(d=g+10,d<b.length&&c(d))};q.onerror=function(b){f++;I(a,b)}}var d=this,e=[],f=0;if(0<b.length)for(var g=0;10>g&&g<b.length;g++)c(g);else H(a,[])};
u.qa=function(a,b,c,d){b=this.e.objectStore(b);w(d)?(d=b.index(d),c=c===p?d.count():d.count(c)):c=c===p?b.count():b.count(c);c.onsuccess=function(b){H(a,b.target.result)};c.onerror=function(b){I(a,b)}};function Ac(){0!=Bc&&ja(this)}var Bc=0;!La||Ya();var Cc=!La||Ya(),Dc=La&&!Wa("9");!Na||Wa("528");Ma&&Wa("1.9b")||La&&Wa("8")||Ka&&Wa("9.5")||Na&&Wa("528");Ma&&!Wa("8")||La&&Wa("9");function Ec(a,b){this.type=a;this.a=this.target=b}Ec.prototype.b=r;Ec.prototype.c=n;Ec.prototype.d=function(){this.c=r};function Fc(a){Fc[" "](a);return a}Fc[" "]=aa();function Gc(a,b){a&&Hc(this,a,b)}D(Gc,Ec);Gc.prototype.target=p;Gc.prototype.h=p;function Hc(a,b,c){var d=a.type=b.type;Ec.call(a,d);a.target=b.target||b.srcElement;a.a=c;if((c=b.relatedTarget)&&Ma)try{Fc(c.nodeName)}catch(e){}a.h=b;b.defaultPrevented&&a.d();delete a.b}Gc.prototype.d=function(){Gc.M.d.call(this);var a=this.h;if(a.preventDefault)a.preventDefault();else if(a.returnValue=r,Dc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};function Ic(){}var Jc=0;Ic.prototype.key=0;Ic.prototype.ja=r;Ic.prototype.a=r;Ic.prototype.handleEvent=function(a){return this.b?this.za.call(this.ib||this.src,a):this.za.handleEvent.call(this.za,a)};var Kc={},Lc={},Mc={},Nc={};
function Oc(a,b,c,d,e){if(b)if(x(b))for(var f=0;f<b.length;f++)Oc(a,b[f],c,d,e);else{d=!!d;var g=Lc;b in g||(g[b]={A:0,v:0});g=g[b];d in g||(g[d]={A:0,v:0},g.A++);var g=g[d],h=ja(a),m;g.v++;if(g[h]){m=g[h];for(f=0;f<m.length;f++)if(g=m[f],g.za==c&&g.ib==e){if(g.ja)break;return}}else m=g[h]=[],g.A++;var l=Pc,q=Cc?function(a){return l.call(q.src,q.key,a)}:function(a){a=l.call(q.src,q.key,a);if(!a)return a},f=q;f.src=a;var t=g=new Ic;ia(c)?t.b=n:c&&c.handleEvent&&ia(c.handleEvent)?t.b=r:j(Error("Invalid listener argument"));
t.za=c;t.c=f;t.src=a;t.type=b;t.capture=!!d;t.ib=e;t.a=r;t.key=++Jc;t.ja=r;c=g.key;f.key=c;m.push(g);Kc[c]=g;Mc[h]||(Mc[h]=[]);Mc[h].push(g);a.addEventListener?(a==v||!a.Bb)&&a.addEventListener(b,f,d):a.attachEvent(b in Nc?Nc[b]:Nc[b]="on"+b,f)}else j(Error("Invalid event type"))}
function Qc(a,b,c,d,e){if(x(b))for(var f=0;f<b.length;f++)Qc(a,b[f],c,d,e);else{d=!!d;a:{f=Lc;if(b in f&&(f=f[b],d in f&&(f=f[d],a=ja(a),f[a]))){a=f[a];break a}a=p}if(a)for(f=0;f<a.length;f++)if(a[f].za==c&&a[f].capture==d&&a[f].ib==e){Rc(a[f].key);break}}}
function Rc(a){if(Kc[a]){var b=Kc[a];if(!b.ja){var c=b.src,d=b.type,e=b.c,f=b.capture;c.removeEventListener?(c==v||!c.Bb)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in Nc?Nc[d]:Nc[d]="on"+d,e);c=ja(c);Mc[c]&&(e=Mc[c],gb(e,b),0==e.length&&delete Mc[c]);b.ja=n;if(b=Lc[d][f][c])b.Lb=n,Sc(d,f,c,b);delete Kc[a]}}}
function Sc(a,b,c,d){if(!d.Ta&&d.Lb){for(var e=0,f=0;e<d.length;e++)d[e].ja?d[e].c.src=p:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.Lb=r;0==f&&(delete Lc[a][b][c],Lc[a][b].A--,0==Lc[a][b].A&&(delete Lc[a][b],Lc[a].A--),0==Lc[a].A&&delete Lc[a])}}function Tc(a,b,c,d,e){var f=1;b=ja(b);if(a[b]){a.v--;a=a[b];a.Ta?a.Ta++:a.Ta=1;try{for(var g=a.length,h=0;h<g;h++){var m=a[h];m&&!m.ja&&(f&=Uc(m,e)!==r)}}finally{a.Ta--,Sc(c,d,b,a)}}return Boolean(f)}function Uc(a,b){a.a&&Rc(a.key);return a.handleEvent(b)}
function Vc(a,b){var c=b.type||b,d=Lc;if(c in d){if(y(b))b=new Ec(b,a);else if(b instanceof Ec)b.target=b.target||a;else{var e=b;b=new Ec(c,a);vb(b,e)}var e=1,f,d=d[c],c=n in d,g;if(c){f=[];for(g=a;g;g=p)f.push(g);g=d[n];g.v=g.A;for(var h=f.length-1;!b.b&&0<=h&&g.v;h--)b.a=f[h],e&=Tc(g,f[h],b.type,n,b)&&b.c!=r}if(r in d)if(g=d[r],g.v=g.A,c)for(h=0;!b.b&&h<f.length&&g.v;h++)b.a=f[h],e&=Tc(g,f[h],b.type,r,b)&&b.c!=r;else for(d=a;!b.b&&d&&g.v;d=p)b.a=d,e&=Tc(g,d,b.type,r,b)&&b.c!=r}}
function Pc(a,b){if(!Kc[a])return n;var c=Kc[a],d=c.type,e=Lc;if(!(d in e))return n;var e=e[d],f,g;if(!Cc){f=b||ca("window.event");var h=n in e,m=r in e;if(h){if(0>f.keyCode||f.returnValue!=k)return n;a:{var l=r;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(q){l=n}if(l||f.returnValue==k)f.returnValue=n}}l=new Gc;Hc(l,f,this);f=n;try{if(h){for(var t=[],A=l.a;A;A=A.parentNode)t.push(A);g=e[n];g.v=g.A;for(var F=t.length-1;!l.b&&0<=F&&g.v;F--)l.a=t[F],f&=Tc(g,t[F],d,n,l);if(m){g=e[r];g.v=g.A;for(F=0;!l.b&&
F<t.length&&g.v;F++)l.a=t[F],f&=Tc(g,t[F],d,r,l)}}else f=Uc(c,l)}finally{t&&(t.length=0)}return f}d=new Gc(b,this);return f=Uc(c,d)};function Wc(){Ac.call(this)}D(Wc,Ac);Wc.prototype.Bb=n;Wc.prototype.addEventListener=function(a,b,c,d){Oc(this,a,b,c,d)};Wc.prototype.removeEventListener=function(a,b,c,d){Qc(this,a,b,c,d)};var Xc=v.window||v.self;function Yc(a,b,c){ia(a)?c&&(a=pa(a,c)):a&&"function"==typeof a.handleEvent?a=pa(a.handleEvent,a):j(Error("Invalid listener argument"));2147483647<b||Xc.setTimeout(a,b||0)};function Zc(a,b){wc.call(this,a,b)}D(Zc,wc);u=Zc.prototype;u.i=s("e");u.pb=function(a,b,c,d){b=ad(this.i(),c,b,d);H(a,b)};u.qb=function(a,b,c,d){for(var e=[],f=0;f<c.length;f++)e[f]=ad(this.i(),c[f],b,w(d)?d[f]:k);H(a,e)};u.Oa=function(a,b,c){H(a,bd(this.i(),b,c))};u.lb=function(a,b,c){for(var d=[],e=0;e<c.length;e++){var f=bd(this.i(),b,c[e]);d.push(f)}H(a,d)};u.mb=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=bd(this.i(),b[d].a,b[d].id);c.push(e)}H(a,c)};u.Sa=aa();
u.bb=function(a,b,c){cd(this.i(),b,c);H(a,n)};u.pa=function(a,b){for(var c=y(b)?[b]:b,d=0;d<c.length;d++)cd(this.e,c[d]);H(a,n)};u.La=function(a,b){Yc(function(){for(var c=[],d=0;d<b.length;d++){var e=dd(this.e,b[d]);c[d]=e.length}H(a,c)},0,this)};u.qa=function(a,b){var c="_database_"+this.ga;w(b)&&(c+="-"+b);var d=0,e;for(e in this.e)this.e.hasOwnProperty(e)&&0==e.lastIndexOf(c,0)&&d++;H(a,d)};function ed(a,b){wc.call(this,a,b)}D(ed,wc);u=ed.prototype;u.n=M("ydn.db.core.req.WebSql");function fd(a,b){var c=Ob(a._default_);if(b.keyPath!=p)for(var d=gd(a[b.keyPath],b.type),e=c,f=0;f<b.a.length;f++){var g=b.a[f];if(f==b.a.length-1){e[g]=d;break}w(e[g])||(e[g]={});e=e[g]}for(d=0;d<b.indexes.length;d++)e=b.indexes[d],"_default_"!=e.name&&(c[e.name]=gd(a[e.name],e.type));return c}u.i=s("e");u.Ib=function(a,b,c,d,e,f){hd(this,a,n,b,k,c,d,e,f)};
u.Gb=function(a,b,c,d,e,f,g){hd(this,a,n,b,c,d,e,f,g)};
function hd(a,b,c,d,e,f,g,h,m){var l=[],q=U(a.a,d);e=w(e)?e:id(q);d=E(e);var t=id(q),A="SELECT "+(c?E(t):"*")+" FROM "+jd(q),F=[];if(f!==p){e=Wb(e,f);A+=" WHERE "+e.sql;for(f=0;f<e.ob.length;f++)F[f]=kd(e.ob[f],q.type)}A+=" ORDER BY "+d+" "+(g?"DESC":"ASC");z(h)&&(A+=" LIMIT "+h);z(m)&&(A+=" OFFSET "+m);a.e.executeSql(A,F,function(a,d){for(var e=0,f=d.rows.length;e<f;e++){var g=d.rows.item(e);c?l[e]=gd(g[t],q.type):g!=p&&(l[e]=fd(g,q))}H(b,l)},function(c,d){J(a.n,"get error: "+d.message);I(b,d);return n})}
u.Jb=function(a,b,c,d,e){hd(this,a,n,b,k,p,c,d,e)};u.pb=function(a,b,c,d){var e=U(this.a,b);e||j(new T(b));var f=this,g=ld(e,c,d);b="INSERT OR REPLACE INTO "+jd(e)+" ("+g.zb.join(", ")+") VALUES ("+g.Pb.join(", ")+");";this.e.executeSql(b,g.Rb,function(b,c){H(a,w(g.key)?g.key:c.insertId)},function(b,c){J(f.n,"put error: "+c.message);I(a,c);return n})};
u.qb=function(a,b,c,d){function e(b,l){var q;q=w(d)?ld(f,c[b],d[b]):ld(f,c[b]);var t="INSERT OR REPLACE INTO "+jd(f)+" ("+q.zb.join(", ")+") VALUES ("+q.Pb.join(", ")+");";l.executeSql(t,q.Rb,function(d,f){h++;g[b]=w(q.key)?q.key:f.insertId;if(h==c.length)H(a,g);else{var l=b+2;l<c.length&&e(l,d)}},function(b,c){I(a,c);return n})}var f=U(this.a,b);f||j(new T(b));var g=[],h=0;if(0<c.length)for(b=0;2>b&&b<c.length;b++)e(b,this.i());else H(a,[])};
u.Oa=function(a,b,c){var d=U(this.a,b),e=this;b=md(d);c=[kd(c,d.type)];b="SELECT * FROM "+jd(d)+" WHERE "+b+" = ?";this.e.executeSql(b,c,function(b,c){if(0<c.rows.length){var e=c.rows.item(0);e!=p?H(a,fd(e,d)):H(a,k)}else H(a,k)},function(b,c){J(e.n,"get error: "+c.message);I(a,c);return n})};
u.lb=function(a,b,c){function d(b,l){var q=c[b],t=md(h),q=[kd(q,h.type)],t="SELECT * FROM "+jd(h)+" WHERE "+t+" = ?";l.executeSql(t,q,function(e,l){g++;if(0<l.rows.length){var q=l.rows.item(0);q!=p&&(f[b]=fd(q,h))}else f[b]=k;g==c.length?H(a,f):(q=b+10,q<c.length&&d(q,e))},function(b,c){J(e.n,"get error: "+c.message);I(a,c);return n})}var e=this,f=[],g=0,h=U(this.a,b);if(0<c.length)for(b=0;10>b&&b<c.length;b++)d(b,this.i());else H(a,[])};u.ya=function(a,b,c,d,e,f){hd(this,a,r,b,k,c,d,e,f)};u.Sa=aa();
u.mb=function(a,b){function c(g,m){var l=b[g],q=U(d.a,l.a),l=x(l.id)?l.id.join("^|"):l.id;md(q);var l=[l],t="SELECT * FROM "+jd(q)+" WHERE "+nd(q)+" = ?";m.executeSql(t,l,function(d,m){f++;if(0<m.rows.length){var l=m.rows.item(0);l!=p&&(e[g]=fd(l,q))}else e[g]=k;f==b.length?H(a,e):(l=g+10,l<b.length&&c(l,d))},function(b,c){J(d.n,"get error: "+c.message);I(a,c);return n})}var d=this,e=[],f=0;if(0<b.length)for(var g=0;10>g&&g<b.length;g++)c(g,this.i());else H(a,[])};
u.pa=function(a,b){function c(b,g){var h=U(d.a,e[b]);h||j(new T(e[b]));h="DELETE FROM  "+jd(h);g.executeSql(h,[],function(d){b==e.length-1?H(a,n):c(b+1,d)},function(b,c){J(d.n,"Sqlite error: "+c.message);I(a,c);return n})}var d=this,e=x(b)&&0<b.length?b:y(b)?[b]:yc(this.a);0<e.length?c(0,this.e):H(a,[])};
u.bb=function(a,b,c){var d=U(this.a,b);d||j(new T(b));var e=this;b="DELETE FROM "+jd(d)+" WHERE "+nd(d)+" = ?";this.e.executeSql(b,[c],function(){H(a,n)},function(b,c){J(e.n,"put error: "+c.message);I(a,c);return n})};
u.La=function(a,b){function c(f){var g="SELECT COUNT(*) FROM "+E(b[f]);d.e.executeSql(g,[],function(d,g){var l=g.rows.item(0);e[f]=parseInt(l["COUNT(*)"],10);f++;f==b.length?H(a,e):c(f)},function(b,c){J(d.n,"count error: "+c.message);I(a,c);return n})}var d=this,e=[];0==b.length?H(a,0):c(0);return a};
u.qa=function(a,b){var c=this,d="SELECT COUNT(*) FROM "+E(b);this.e.executeSql(d,[],function(b,c){var d=c.rows.item(0);H(a,d["COUNT(*)"])},function(b,d){J(c.n,"count error: "+d.message);I(a,d);return n});return a};u.toString=function(){return"WebSqlEx:"+(this.ga||"")};/*
 _try.
*/
function od(a){this.b=a;this.c=[];this.V=new pd}u=od.prototype;u.yc=M("ydn.db.tr.TxStorage");u.vb=function(){return this.b.vb()};u.ab=function(a){return this.b.ab(a)};u.ba=function(a,b,c,d){this.b.ba(a,b,c,d)};u.V=p;u.da=s("b");u.i=function(){return this.V.a&&!this.V.b?this.V.i():p};u.type=function(){return this.b.type()};
u.$=function(a,b,c,d,e){var f=a.name||"",g=b;y(b)?g=[b]:(!x(b)||0<b.length&&!y(b[0]))&&j(new P("storeNames"));var h=w(c)?c:R,m=a;if(4<arguments.length){var l=Array.prototype.slice.call(arguments,4),m=function(){var b=Array.prototype.slice.call(arguments),b=b.concat(l);return a.apply(this,b)};m.name=f}var q=this;this.V.a?this.c.push({gb:4<arguments.length?m:a,kc:b,mode:h,L:d}):this.b.ba(function(a){q.m=n;var b=q.V;b.a=a;b.b=r;b.L=p;L(b.c,b+": open");m(q)},g,h,function(a,b){try{ia(d)&&d(a,b)}catch(c){}finally{var e=
q.V;e.a?(L(e.c,e+": close"),e.a=p,ia(e.L)&&e.L(a,b),e.L=p):J(e.c,e+" has no TX to be unlocked for "+a);q.m=r;var e=q,f=e.c.shift();f&&e.$(f.gb,f.kc,f.mode,f.L);ra()}})};u.toString=function(){return"ydn.db.tr.TxStorage:"+this.b.J()};function V(a,b,c,d){od.call(this,a);this.a=d}D(V,od);u=V.prototype;u.da=function(){return V.M.da.call(this)};u.J=function(){return this.d=this.d||this.da().J()};u.l=p;u.ha=function(){if(this.l)return this.l;var a=this.type();"indexeddb"==a?this.l=new xc(this.J(),this.a):"websql"==a?this.l=new ed(this.d,this.a):"memory"==a||"localstorage"==a||"sessionstorage"==a?this.l=new Zc(this.d,this.a):j(new pc("No executor for "+a));return this.l};
u.f=function(a,b,c,d){var e=this,f=this.V;if(f.a&&!f.b)e.ha().e=f.i(),a(e.ha());else{var g=function(){e.D=n;f.a||j(new pc("Tx not active for scope: "+d));f.b&&j(new pc("Tx not available for scope: "+d));e.ha().e=f.i();a(e.ha());L(f.c,f+": locked");f.b=n};g.name=d;e.$(g,b,c,aa())}};
u.$a=function(a,b,c){var d=new G,e,f,g;if(w(a))if(x(a)){(w(c)||w(b))&&j(new P("too many arguments."));e=a;for(a=0;a<e.length;a++)qd(this.a,e[a])||j(new T(e[a]));this.f(function(a){a.La(d,e)},e,R,"countStores")}else y(a)?(qd(this.a,a)||j(new T(a)),e=[a],y(b)?(f=b,g=Tb(c)):B(b)||!w(b)?(w(c)&&j(new P),g=Tb(b)):j(new P("key range")),this.f(function(a){a.qa(d,e[0],g,f)},e,R,"countKeyRange")):j(new P);else{(w(c)||w(b))&&j(new P("too many arguments."));e=yc(this.a);var h=new G;this.f(function(a){a.La(d,
e)},e,R,"countStores");d.R(function(a){a=a.reduce(function(a,b){return b+a},0);H(h,a)},function(a){I(h,a)});return h}return d};u.ca=function(a,b){var c=new G;if(a instanceof vc){var d=a.a;if(!qd(this.a,d)){if(this.a.a())return sb(k);j(new P("Store: "+d+" not found."))}var e=a.id;this.f(function(a){a.Oa(c,d,e)},[d],R,"getById")}else if(y(a)&&w(b)){if(!U(this.a,a)){if(this.a.a())return sb(k);j(new P("Store: "+a+" not found."))}this.f(function(d){d.Oa(c,a,b)},[a],R,"getById")}else j(new P);return c};
u.keys=function(a,b,c,d,e,f,g){var h,m,l,q,t,A=new G;!w(b)||ha(b)?(q=!!b,z(c)?m=c:(w(c)&&j(new TypeError("arg3")),m=1E6),z(d)?l=d:(w(d)&&j(new TypeError("arg4")),l=0),this.f(function(b){b.Jb(A,a,q,m,l)},[a],R,"keysByStore")):B(b)||b===p?(B(b)&&(h=Tb(b)),ha(c)||!w(c)?(q=!!c,z(d)?m=d:(w(d)&&j(new P("arg4 must be number|undefined.")),m=1E6),z(e)?l=e:(w(e)&&j(new P("arg5 must be number|undefined.")),l=0),(w(f)||w(g))&&j(new P("too many arguments")),this.f(function(b){b.Ib(A,a,h,q,m,l)},[a],R,"keysByKeyRange")):
j(new P("arg3 must be boolean|string|undefined."))):y(b)?(!w(c)||c===p||B(c)?h=Tb(c):j(new P("arg3 must be IDBKeyRange|null|undefined.")),w(d)&&!ha(d)&&j(new P("arg4 must be boolean|undefined.")),q=!!d,z(e)?m=e:(w(e)&&j(new P("arg5 must be number|undefined.")),m=1E6),z(f)?l=f:(w(f)&&j(new P("arg6 must be number|undefined.")),l=0),w(g)&&!ha(g)&&j(new P("arg7 must be boolean|undefined.")),t=!!g,this.f(function(c){c.Gb(A,a,b,h,q,m,l,t)},[a],R,"keysByIndexKeyRange")):j(new P);return A};
u.ma=function(a,b,c,d,e,f,g){var h=new G,m,l,q,t;if(y(a)){if(!U(this.a,a)){if(this.a.a())return sb(k);j(new P("Store: "+a+" not found."))}if(x(b))this.f(function(c){c.lb(h,a,b)},[a],R,"listByIds");else if(!w(b)||ha(b))m=!!b,w(c)?z(c)?l=c:j(new P("arg3 must be number|undefined.")):l=1E6,w(d)?z(d)?q=d:j(new P("arg4 must be number|undefined.")):q=0,w(e)&&j(new P("too many input arguments")),this.f(function(b){b.ya(h,a,p,m,l,q)},[a],R,"listByKeyRange");else if(B(b)||b===p||!w(b)){var A=Tb(b);w(c)&&!ha(c)&&
j(new P("arg3 must be boolean|undefined."));m=!!c;w(d)?z(d)?l=d:j(new P("arg4 must be number|undefined.")):l=1E6;w(e)?z(e)?q=e:j(new P("arg5 must be number|undefined.")):q=0;var F=A;this.f(function(b){b.ya(h,a,F,m,l,q)},[a],R,"listByKeyRange")}else y(b)?(A=Tb(c),w(d)&&!ha(d)&&j(new P("arg4 must be boolean|undefined.")),m=!!d,w(e)?z(e)?l=e:j(new P("arg5 must be number|undefined.")):l=1E6,w(f)?z(f)?q=f:j(new P("arg6 must be number|undefined.")):q=0,t=!!g,w(g)&&!ha(g)&&j(new P("arg7 must be boolean|undefined.")),
this.f(function(c){c.Sa(h,a,b,A,m,l,q,t)},[a],R,"listByKeyRange")):j(new P("arg2"))}else if(x(a))if(a[0]instanceof vc){c=[];for(d=0;d<a.length;d++){e=a[d].a;if(!qd(this.a,e)){if(this.a.a())return c=[],c[a.length-1]=k,sb(c);j(new P("Store: "+e+" not found."))}0<=ab(c,e)||c.push(e)}this.f(function(b){b.mb(h,a)},c,R,"listByKeys")}else j(new P("must be array of ydn.db.Key"));else j(new P);return h};
u.Fa=function(a,b,c){var d=y(a)?a:B(a)?a.name:k;y(d)||j(new P("store name"));var e=U(this.a,d);e?this.a.a()&&B(a)&&(a=rd(a),(a=sd(e,a))&&j(new dc("schema change: "+a))):(this.a.a()||j(new P("Not found: "+d)),e=rd(B(a)?a:{name:d}),L(this.yc,"Adding object store: "+d),this.ab(e));var f=new G;e||j(new P("Store: "+d+" not exists."));y(e.keyPath)&&w(c)&&j(new P("key cannot provide while in-line key is in used."));e.autoIncrement&&w(c)&&j(new P("key cannot provide while autoIncrement is true."));!y(e.keyPath)&&
(!e.autoIncrement&&!w(c))&&j(new P("out-of-line key must be provided."));x(b)?this.f(function(a){a.qb(f,d,b,c)},[d],$b,"putObjects"):B(b)?this.f(function(a){a.pb(f,d,b,c)},[d],$b,"putObject"):j(new P);return f};
u.clear=function(a,b){var c=new G;if(y(a))y(b)||z(b)||x(b)?this.f(function(d){d.bb(c,a,b)},[a],$b,"clearById"):(w(b)&&j(new P),this.f(function(b){b.pa(c,a)},[a],$b,"clearByStore"));else if(x(a)&&y(a[0])){var d=a;this.f(function(a){a.pa(c,d)},d,$b,"clearByStore")}else w(a)&&j(new P),d=yc(this.a),this.f(function(a){a.pa(c,d)},d,$b,"clearByStore");return c};u.toString=function(){return"TxStorage:"+this.da().J()};function td(a,b,c,d,e){"transaction"in a?(this.D=a,this.h=this.m=p):"objectStore"in a?(this.D=p,this.m=a.db,this.h=a):j(new P);this.ua=b;this.c=c;this.U=e;this.Ra=d;this.b=[];this.d=r}td.prototype.a=M("ydn.db.con.IdbCursorStream");td.prototype.d=r;td.prototype.b=[];
function ud(a,b){b.onsuccess=function(b){if(b=b.target.result)if(ia(a.U)?a.Ra?a.U(b.primaryKey,b.key):a.U(b.primaryKey,b.value):J(a.a,"sink gone, dropping value for: "+b.primaryKey),0<a.b.length)b["continue"](a.b.shift())};b.onerror=function(){J(a.a,"seeking fail. "+("error"in b?b.error.name+":"+b.error.message:""))}}
td.prototype.seek=function(a){this.b.push(a);if(!this.d){var b=this,c=function(a,c){b.h=p;"complete"!==a&&J(b.a,c.name+":"+c.message);L(b.a,b+" transaction "+a)},d=function(a){var c=b.b.shift();L(b.a,b+" transaction started for "+c);a=a.objectStore(b.ua);var d=a.indexNames;w(b.c)&&d.contains(b.c)?(a=a.index(b.c),b.Ra?ud(b,a.openKeyCursor(c)):ud(b,a.openCursor(c))):!w(b.c)||b.c==a.keyPath?ud(b,a.openCursor(c)):j(new qc)};this.h?(L(b.a,b+" using existing tx."),d(this.h)):this.m?(L(b.a,b+" creating tx from IDBDatabase."),
this.e=this.m.transaction([this.ua],R),this.e.oncomplete=function(a){c("complete",a)},this.e.onerror=function(a){c("error",a)},this.e.onabort=function(a){c("abort",a)}):this.D?(L(b.a,b+" creating tx from ydn.db.con.IStorage."),this.d=n,this.D.ba(function(a){b.d=r;d(a)},[b.ua],R,c)):j(new fc("no way to create a transaction provided."))}};function vd(a,b,c,d){this.b=b;this.c=y(c)?c:k;"transaction"in a?(this.Ea=a,this.a=p):"db"in a?(this.Ea=p,wd(this,a)):j(new P);this.a=p;this.Xa=y(c);this.d=d||k;this.Ca=[];this.sb=[];this.kb=r}u=vd.prototype;u.Ea=p;u.Xa=n;u.tb=p;u.sb=[];u.Ca=[];function wd(a,b){"db"in b?a.a=new td(b,a.b,a.c,a.Xa,pa(a.cb,a)):j(new P)}function xd(a){var b=0<a.Ca.length;if(b&&!a.kb&&ia(a.tb)){var c=function(){xd(a)},d=a.sb.shift(),e=a.Ca.shift(),b=0<a.Ca.length,c=a.tb(d,e,b?c:p);b&&!c&&xd(a)}}u.kb=r;
u.cb=function(a,b){this.sb.push(a);this.Ca.push(b);xd(this)};u.push=function(a,b){this.kb&&j(new ic("collecting"));if(2<=arguments.length)this.cb(a,b);else{if(!this.a){this.Ea||j(new ic("No database set."));var c=this.Ea.type();c?"indexeddb"===c?this.a=new td(this.Ea,this.b,this.c,this.Xa,pa(this.cb,this)):j(new ec(c)):j(new ic("Database not connected."))}this.a.seek(a)}};u.toString=function(){return"Streamer:"+this.b+(this.c||"")};function yd(a,b,c,d,e){this.Q=a;this.F=b;this.s=c;this.na="prev"==d||"prevunique"==d;this.P=d;this.wa=e}u=yd.prototype;u.F="";u.Q="";u.P="";u.s=p;u.na=r;u.wa=n;u.G=function(a){j(a)};u.r=function(a,b,c){this.q(a,b,c)};u.q=aa();u.jb=r;u.toString=function(){return 'yd.M.toString.call(this)';};var zd={};
function Ad(a){a=[a];for(var b=new Bd,c=0,d,e;(e=a.pop())!==k;){0===c%4&&12<c+4&&(b.write(c),c=0);d=typeof e;if(e instanceof Array)if(c+=4,0<e.length){a.push(zd);for(d=e.length;d--;)a.push(e[d]);continue}else b.write(c);else if("number"===d)c+=1,b.write(c),Cd(b,e);else if(e instanceof Date)c+=2,b.write(c),Cd(b,e.valueOf());else if("string"===d){c+=3;b.write(c);c=b;for(d=0;d<e.length;d++){var f=e.charCodeAt(d);126>=f?c.write(f+1):16510>=f?(f-=127,c.write(128|f>>8,f&255)):c.write(192|f>>10,f>>2|255,
(f|3)<<6)}c.write(0)}else if(e===zd)b.write(0);else return"";c=0}return b.trim().toString()}
function Cd(a,b){var c,d,e;c=b;var f=e=d=0;if(0!==c)if(isFinite(c)){0>c&&(d=1,c=-c);f=0;if(2.2250738585072014E-308<=c){for(e=c;1>e;)f--,e*=2;for(;2<=e;)f++,e/=2;e=f+1023}f=e?Math.floor(4503599627370496*(c/Math.pow(2,f)-1)):Math.floor(c/4.9E-324)}else e=2047,isNaN(c)?f=0x8000000000000:-Infinity===c&&(d=1);c=d;d=e;e=f;c&&(e=0xfffffffffffff-e,d=2047-d);a.write((c?0:128)|d>>4);a.write((d&15)<<4|0|e/281474976710656);e%=281474976710656;c=0|e/4294967296;a.write(c>>8,c&255);e%=4294967296;c=0|e/65536;a.write(c>>
8,c&255);c=e%65536;a.write(c>>8,c&255)}function Dd(a){var b=a.Z()|0,c=b>>7?r:n,d=c?-1:1,e=(b&127)<<4,b=a.Z()|0,e=e+(b>>4);c&&(e=2047-e);for(var b=[c?15-(b&15):b&15],f=6;f--;)b.push(c?255-(a.Z()|0):a.Z()|0);a=0;for(f=7;f--;)a=a/256+b[f];a/=16;return 0===a&&0===e?0:(a+1)*Math.pow(2,e-1023)*d}
function Ed(a){for(var b=[],c=0,d=0,e=0,f,g;;){f=a.Z();if(0===f||f==p)break;0===c?(g=f>>6,2>g&&!isNaN(f)?b.push(String.fromCharCode(f-1)):(c=g,d=f<<10,e++)):2===c?(b.push(String.fromCharCode(d+f+127)),c=d=e=0):2===e?(d+=f<<2,e++):(b.push(String.fromCharCode(d|f>>6)),c=d=e=0)}return b.join("")}function Fd(a){this.a=p;var b=a.length-1,c=-1;this.Z=function(){return this.a=c<b?parseInt(a[++c]+a[++c],16):p}}
function Bd(){var a=[],b;this.write=function(c){for(var d=0;d<arguments.length;d++)b=arguments[d].toString(16),a.push(2===b.length?b:b="0"+b)};this.toString=function(){return a.length?a.join(""):p};this.trim=function(){for(var b=a.length;"00"===a[--b];);a.length=++b;return this}};function Gd(a,b,c,d,e){!w(a)&&w(e)&&(a=e);ga(a)?(a=bb(a,function(a){return a}),w(e)||(e=a.join(", "))):y(a)||j(new P("index keyPath or name required."));this.keyPath=a;this.name=w(e)?e:this.keyPath;this.type=Hd(b);this.type!=b&&j(new P("Invalid index type: "+b+" in "+this.name));this.unique=!!c;this.multiEntry=!!d}var Id=String.fromCharCode(31);
function kd(a,b){if("DATE"==b){if(a instanceof Date)return+a}else{if("ARRAY"==b){var c=a==p?[""]:x(a)?a:[a],d=c[0]instanceof Date?"d":z(c[0])?"n":"t",c="d"==d?c.reduce(function(a,b){return a+ +b},""):c.join(Id);return d+Id+c+Id}return w(b)?a:"X'"+Ad(a)+"'"}}
function gd(a,b){if("DATE"==b)return new Date(a);if("ARRAY"==b){var c=a.split(Id),d=c[0],c=c.slice(1,c.length-1);return bb(c,function(a){return"d"==d?new Date(parseInt(a,10)):"n"==d?parseFloat(a):a})}if(w(b))c=a;else{for(var e=c=[],f,g=[],h,m,l=new Fd(a);l.Z()!=p;)if(0===l.a)e=g.pop();else{if(l.a===p)break;do{h=l.a/4|0;f=l.a%4;for(var q=0;q<h;q++)m=[],e.push(m),g.push(e),e=m;if(0===f&&12<l.a+4)l.Z();else break}while(1);1===f?e.push(Dd(l)):2===f?e.push(new Date(Dd(l))):3===f?e.push(Ed(l)):0===f&&(e=
g.pop())}c=c[0]}return c}var Jd="ARRAY BLOB DATE INTEGER NUMERIC TEXT".split(" ");function Hd(a){a=ab(Jd,a);return Jd[a]}Gd.prototype.toJSON=function(){return{name:this.name,keyPath:this.keyPath,type:this.type,unique:this.unique,multiEntry:this.multiEntry}};
function Kd(a,b,c,d,e){this.name=a;y(this.name)||j(new P("store name must be a string"));this.keyPath=w(b)?b:p;this.keyPath!==p&&(!y(this.keyPath)||x(this.keyPath))&&j(new P("keyPath must be a string or array"));this.autoIncrement=c;var f;w(d)&&(f=Hd(d),w(f)||j(new P("type invalid in store: "+this.name)));this.type=w(f)?f:this.autoIncrement?"INTEGER":k;this.a=y(this.keyPath)?this.keyPath.split("."):[];this.indexes=e||[]}
Kd.prototype.toJSON=function(){for(var a=[],b=0;b<this.indexes.length;b++)a.push(this.indexes[b].toJSON());return{name:this.name,keyPath:this.keyPath,autoIncrement:this.autoIncrement,type:this.type,indexes:a}};function rd(a){var b=[],c=a.indexes||[];if(x(c))for(var d=0;d<c.length;d++){var e=new Gd(c[d].keyPath,c[d].type,c[d].unique,c[d].multiEntry,c[d].name);w(e.keyPath)&&e.keyPath===a.keyPath||b.push(e)}return new Kd(a.name,a.keyPath,a.autoIncrement,a.type,b)}
function Ld(a,b){return db(a.indexes,function(a){return a.name==b})}function Md(a,b){return b==a.keyPath?n:cb(a.indexes,function(a){return a.name==b})}function nd(a){return y(a.keyPath)?E(a.keyPath):k}function md(a){return y(a.keyPath)?E(a.keyPath):"_ROWID_"}function id(a){return y(a.keyPath)?a.keyPath:"_ROWID_"}function jd(a){return E(a.name)}
function ld(a,b,c){var d=[];c=w(c)?c:y(a.keyPath)?tb(b,a.a):k;var e=[];w(c)&&(e=a.keyPath!=p?[nd(a)]:["_ROWID_"],d=[kd(c,a.type)]);for(var f=0;f<a.indexes.length;f++)if(!(a.indexes[f].name==a.keyPath||"_default_"==a.indexes[f].name)){var g=b[a.indexes[f].name];w(g)&&(d.push(kd(g,a.indexes[f].type)),e.push(E(a.indexes[f].name)))}var f={},h;for(h in b)b.hasOwnProperty(h)&&!Md(a,h)&&(f[h]=b[h]);d.push(JSON.stringify(f));e.push("_default_");a=[];for(f=d.length-1;0<=f;f--)a[f]="?";return{zb:e,Pb:a,Rb:d,
key:c}}
function sd(a,b){if(!b)return"missing store: "+a.name;if(a.name!=b.name)return"store name, expect: "+a.name+", but: "+b.name;if(a.keyPath!=b.keyPath)return"keyPath, expect:  "+a.keyPath+", but: "+b.keyPath;if(w(a.autoIncrement)&&w(b.autoIncrement)&&a.autoIncrement!=b.autoIncrement)return"autoIncrement, expect:  "+a.autoIncrement+", but: "+b.autoIncrement;if(a.indexes.length!=b.indexes.length)return"indexes length, expect:  "+a.indexes.length+", but: "+b.indexes.length;if(w(a.type)&&w(b.type)&&a.type!=
b.type)return"data type, expect:  "+a.type+", but: "+b.type;for(var c=0;c<a.indexes.length;c++){var d=Ld(b,a.indexes[c].name),d=!d?"no index for "+a.indexes[c].name:a.indexes[c].name!=d.name?"name, expect: "+a.indexes[c].name+", but: "+d.name:!Pb(a.indexes[c].keyPath,d.keyPath)?"keyPath, expect: "+a.indexes[c].keyPath+", but: "+d.keyPath:a.indexes[c].unique!=d.unique?"unique, expect: "+a.indexes[c].unique+", but: "+d.unique:w(a.indexes[c].type)&&w(d.type)&&a.indexes[c].type!=d.type?"data type, expect: "+
a.indexes[c].type+", but: "+d.type:"";if(0<d.length)return'index "'+a.indexes[c].name+'" '+d}return""}function Nd(a,b){var c,d=b;if(B(a)){c=a.version;for(var d=[],e=a.stores||[],f=0;f<e.length;f++){var g=rd(e[f]);d.push(g)}}else y(a)?c=0==a.length?k:parseFloat(a):z(a)&&(c=a);w(c)&&((!z(c)||0>c)&&j(new P("Invalid version: "+c+" ("+a+")")),isNaN(c)&&(c=k));w(b)&&(!x(b)||0<b.length&&!(b[0]instanceof Kd))&&j(new P("stores"));this.version=c;this.b=!w(this.version);this.stores=d||[]}
Nd.prototype.toJSON=function(){var a=this.stores.map(function(a){return a.toJSON()});return{version:this.version,stores:a}};Nd.prototype.b=r;Nd.prototype.a=ba(r);function yc(a){return a.stores.map(function(a){return a.name})}Nd.prototype.c=function(a){return this.stores[a]||p};function U(a,b){return db(a.stores,function(a){return a.name==b})}function qd(a,b){return cb(a.stores,function(a){return a.name==b})}
function Od(a,b){if(!b||a.stores.length!=b.stores.length)return"Number of store: "+a.stores.length+" vs "+b.stores.length;for(var c=0;c<a.stores.length;c++){var d=U(b,a.stores[c].name),d=sd(a.stores[c],d);if(0<d.length)return'store: "'+a.stores[c].name+'" '+d}return""};function Pd(a,b){w(a)&&5242880<a&&J(this.g,"storage size request ignored.");this.k=p;this.Wa=b||18E4}
Pd.prototype.la=function(a,b){function c(a,c,d){K(e.g,(d?"changing":"upgrading")+" version to "+a.version+" from "+(b.a()?"auto":b.version));for(d=0;d<b.stores.length;d++)Qd(e,a,c,b.stores[d])}function d(a,b){w(b)?(J(e.g,b?b.message:"Error received."),e.k=p,I(f,b)):(e.k=a,e.k.onabort=function(a){L(e.g,e+": onabort - "+a.message)},e.k.onerror=function(a){L(e.g,e+": onerror - "+a.message)},e.k.onversionchange=function(a){L(e.g,e+": onversionchange to: "+a.version);e.k&&(e.k.onabort=p,e.k.onerror=p,
e.k.onversionchange=p,e.k.close(),e.k=p,ia(e.b)&&e.b())},H(f,n))}var e=this,f=new G,g=b.version;K(e.g,"Opening database: "+a+" ver: "+g);var h;h=w(g)?W.open(a,g):W.open(a);h.onsuccess=function(f){var g=f.target.result;K(e.g,"Database: "+g.name+", ver: "+g.version+" opened.");if(b.b)e.O(function(f){if(b.a())for(var h=0;h<f.stores.length;h++)if(!qd(b,f.stores[h].name)){var m=rd(f.stores[h].toJSON());b.stores.push(m)}f=Od(b,f);if(0<f.length){K(e.g,"Schema change require for difference in "+f);var q=
z(g.version)?g.version+1:1;if("IDBOpenDBRequest"in v){g.close();var N=W.open(a,q);N.onupgradeneeded=function(a){a=a.target.result;K(e.g,"re-open for version "+a.version);c(a,N.transaction,r)};N.onsuccess=function(a){d(a.target.result)};N.onerror=function(){K(e.g,e+": fail.");d(p)}}else{var da=g.setVersion(q+"");da.a=function(a){J(e.g,"migrating from "+g.version+" to "+q+" failed.");d(p,a)};da.onsuccess=function(){da.transaction.oncomplete=ya;c(g,da.transaction,n)};var ya=function(){var b=W.open(a);
b.onsuccess=function(a){a=a.target.result;K(e.g,e+": OK.");d(a)};b.onerror=function(){K(e.g,e+": fail.");d(p)}};da.transaction!=p&&(da.transaction.oncomplete=ya)}}else d(g)},k,g);else if(b.version>g.version){var h=g.setVersion(b.version);h.a=function(a){J(e.g,"migrating from "+g.version+" to "+b.version+" failed.");d(p,a)};h.onsuccess=function(){c(g,h.transaction,n)}}else b.version==g.version?K(e.g,"database version "+g.version+" ready to go"):J(e.g,"connected database version "+g.version+" is higher than requested version."),
e.O(function(a){a=Od(b,a);0<a.length?(K(e.g,a),d(p,new gc("different schema: "+a))):d(g)},k,g)};h.onupgradeneeded=function(a){a=a.target.result;K(e.g,"upgrade needed for version "+a.version);c(a,h.transaction,r)};h.onerror=function(c){Lb(e.g,"opening database "+a+":"+b.version+" failed.");d(p,c)};h.onblocked=function(c){Lb(e.g,"database "+a+" "+b.version+" block, close other connections.");d(p,c)};z(this.Wa)&&Yc(function(){"done"!=h.readyState&&(Lb(e.g,e+": database state is still "+h.readyState),
d(p,Error("connection timeout after "+e.Wa)))},this.Wa);return f};var W=v.indexedDB||v.mozIndexedDB||v.webkitIndexedDB||v.moz_indexedDB||v.msIndexedDB;u=Pd.prototype;u.Wa=18E4;u.type=ba("indexeddb");u.ub=function(){return!!this.k};u.g=M("ydn.db.con.IndexedDb");u.k=p;
u.O=function(a,b,c){c=c||this.k;if(w(b)){if(b===p){if(0==c.objectStoreNames.length){a(new Nd(c.version));return}j(new fc)}c=b.db}else{b=[];for(var d=c.objectStoreNames.length-1;0<=d;d--)b[d]=c.objectStoreNames[d];if(0==b.length){a(new Nd(c.version));return}b=c.transaction(b,R)}for(var e=c.objectStoreNames,f=[],g=e.length,d=0;d<g;d++){for(var h=b.objectStore(e[d]),m=[],l=0,q=h.indexNames.length;l<q;l++){var t=h.index(h.indexNames[l]);m[l]=new Gd(t.keyPath,k,t.unique,t.multiEntry,t.name)}f[d]=new Kd(h.name,
h.keyPath,h.autoIncrement,k,m)}b=new Nd(c.version,f);a(b)};
function Qd(a,b,c,d){function e(){var a={autoIncrement:!!d.autoIncrement};d.keyPath!=p&&(a.keyPath=d.keyPath);try{return b.createObjectStore(d.name,a)}catch(c){j(c)}}L(a.g,"Creating Object Store for "+d.name+" keyPath: "+d.keyPath);if(b.objectStoreNames.contains(d.name)){c=c.objectStore(d.name);c.keyPath!=d.keyPath?(b.deleteObjectStore(d.name),J(a.g,"store: "+d.name+" deleted due to keyPath change."),c=e()):c.autoIncrement!=d.autoIncrement&&(b.deleteObjectStore(d.name),J(a.g,"store: "+d.name+" deleted due to autoIncrement change."),
c=e());for(var f=c.indexNames,g=0,h=0,m=0;m<d.indexes.length;m++){var l=d.indexes[m];f.contains(l.name)||(c.createIndex(l.name,l.keyPath,{unique:l.unique}),g++)}for(m=0;m<f.length;m++)Md(d,f[m])||(c.deleteIndex(f[m]),h++);L(a.g,"Updated store: "+c.name+", "+g+" index created, "+h+" index deleted.")}else{c=e();for(m=0;m<d.indexes.length;m++)l=d.indexes[m],L(a.g,"Creating index: "+l.name+" multiEntry: "+l.multiEntry),l.unique||l.multiEntry?c.createIndex(l.name,l.keyPath,{unique:l.unique,multiEntry:l.multiEntry}):
c.createIndex(l.name,l.keyPath);L(a.g,"Created store: "+c.name+" keyPath: "+c.keyPath)}}u.Ma=function(a,b,c,d){var e=this.k;if(!b){b=[];for(var f=e.objectStoreNames.length-1;0<=f;f--)b[f]=e.objectStoreNames[f]}0==b.length&&a(p);b=e.transaction(b,c);b.oncomplete=function(a){d("complete",a)};b.onerror=function(a){d("error",a)};b.onabort=function(a){d("abort",a)};a(b)};u.Ya=function(){this.k.close()};u.toString=function(){var a=this.k?this.k.name+":"+this.k.version:"";return this.type()+":"+a};function Rd(a){this.a=w(a)?a:4194304}u=Rd.prototype;
u.la=function(a,b){function c(a,b){w(b)?(d.I=p,I(e,b)):(d.I=a,H(e,n))}var d=this,e=new G,f=p;try{var g=b.b?"":b.version+"",f=v.openDatabase(a,"",a,this.a)}catch(h){"SECURITY_ERR"==h.name?(J(this.p,"SECURITY_ERR for opening "+a),f=p,this.wb=new tc(h)):j(h)}if(f){f.version===g?L(this.p,"Existing database version "+f.version+" opened."):L(d.p,"Database version "+f.version+" opened, but require "+g+" version.");!b.b&&f.version<g&&L(d.p,"Upgrading to version: "+g);var m=f;L(d.p,a+": setting version from "+
m.version+" to "+b.version);var l=0;m.transaction(function(a){d.O(function(c){for(var e=0;e<b.stores.length;e++){var f=U(c,b.stores[e].name);Sd(d,a,b.stores[e],function(){l++},f)}},a,m)},function(a){j(a)},function(){l!=b.stores.length?J(d.p,a+": setting version voided."):(L(d.p,a+": ready."),c(m))})}else c(p,this.wb);return e};u.type=ba("websql");u.wb=p;u.I=p;u.p=M("ydn.db.con.WebSql");
u.O=function(a,b,c){function d(a,b){j(b)}function e(b,c){for(var d=0;d<c.rows.length;d++){var e=c.rows.item(d);if("__WebKitDatabaseInfoTable__"!=e.name&&"table"==e.type){for(var h=e.sql.substr(e.sql.indexOf("("),e.sql.lastIndexOf(")")).match(/(?:"[^"]*"|[^,])+/g),F="",Q,N=[],da=r,ya=0;ya<h.length;ya++){var ea=h[ya].match(/\w+|"[^"]+"/g),la=za(ea[0],'"'),Ia=Hd(ea[1]);-1!=ea.indexOf("PRIMARY")&&-1!=ea.indexOf("KEY")?(F=la,Q=Ia,-1!=ea.indexOf("AUTOINCREMENT")&&(da=n)):"_default_"!=la&&(ea=new Gd(la,
Ia,"UNIQUE"==ea[2]),N.push(ea))}e=new Kd(e.name,F,da,Q,N);g.push(e)}}d=new Nd(f,g);a(d)}var f=(c=c||this.I)&&c.version?parseInt(c.version,10):k,f=isNaN(f)?k:f,g=[];if(b)b.executeSql("SELECT * FROM sqlite_master",[],e,d);else{var h=this;c.readTransaction(function(b){h.O(a,b,c)},function(a){Lb(h.p,"opening tx: "+a.message);j(a)},e)}};
function Sd(a,b,c,d,e){function f(a){b.executeSql(a,[],function(){F++;F==l.length&&d(n)},function(b,d){j(new sc(d,"Error creating table: "+c.name+" "+a))})}var g="CREATE TABLE IF NOT EXISTS "+jd(c)+" (",h=nd(c)||"_ROWID_",m=c.type||"BLOB";"ARRAY"==m&&(m="TEXT");c.keyPath!=p?(g+=nd(c)+" "+m+" UNIQUE PRIMARY KEY ",c.autoIncrement&&(g+=" AUTOINCREMENT ")):g=c.autoIncrement?g+("_ROWID_ "+m+" UNIQUE PRIMARY KEY AUTOINCREMENT "):g+("_ROWID_ "+m+" UNIQUE PRIMARY KEY ");for(var g=g+" ,_default_ BLOB",l=[],
m=0;m<c.indexes.length;m++){var q=c.indexes[m],t=q.unique?" UNIQUE ":" ",A="CREATE "+t+" INDEX IF NOT EXISTS "+E(q.name)+" ON "+jd(c)+" ("+h+")";l.push(A);q.keyPath!=c.keyPath&&(g+=", "+E(q.keyPath)+" "+(q.type||"BLOB")+t)}l.unshift(g+");");var F=0,g="Create";if(e){if(0==sd(c,e).length){L(a.p,c.name+" exists.");d(n);return}g="Modify"}L(a.p,g+" table: "+c.name+": "+l.join(";"));for(a=0;a<l.length;a++)f(l[a])}u.ub=function(){return!!this.I};u.Ya=aa();
u.Ma=function(a,b,c,d){function e(a){L(h.p,h+": Tx "+c+" request cause error.");d("error",a)}function f(){d("complete",{type:"complete"})}function g(b){a(b)}var h=this;this.I===p&&(a(p),d("error",this.wb));c==R?this.I.readTransaction(g,e,f):c==ac?this.I.changeVersion(this.I.version,this.I.version+1+"",g,e,f):this.I.transaction(g,e,f)};function nc(a,b){if(W)return W.cmp(a,b);a=Ad(a);b=Ad(b);return a>b?1:a==b?0:-1};function Td(a,b){this.a=a||p;this.b=b;this.c=0}Td.prototype.a=p;Td.prototype.Ka=ba(r);function Ud(a,b,c){for(var d=c[0],e=1;e<c.length;e++)if(c[e]!=p){if(d!=p&&0!=nc(c[e],d)){d=p;break}}else d=p;return d!=p&&(a.c++,a.a&&a.a.push(d),w(a.b)&&a.c>=a.b)?[]:b}Td.prototype.Va=function(){return[]};function Vd(a,b,c,d,e,f){yd.call(this,b,c,d,e,f);this.Y=a;this.index=p;c!=p&&(a.indexNames.contains(c)?this.index=a.index(c):a.keyPath!=c&&j(new pc('index "'+c+'" not found in '+a.name)));this.W=this.N=this.j=p;this.ka=r}D(Vd,yd);u=Vd.prototype;u.oa=M("ydn.db.index.req.IDBCursor");u.Y=p;u.index=p;u.j=p;
u.hc=function(a){var b="IDBCursor: "+this.Q+":"+this.F;if(this.j=a=a.target.result){if(this.W!=p){b=W.cmp(a.key,this.W);if(1===b){this.W=this.N=p;this.r(a.primaryKey,a.key,a.value);return}if(0===b)this.W=p;else{a["continue"]();return}}if(this.N!=p)if(b=W.cmp(this.N,a.primaryKey),0===b)this.N=p,this.ka?(this.ka=r,a["continue"]()):this.r(a.primaryKey,a.key,a.value);else if(1===b)a["continue"]();else this.N=p,this.r(a.primaryKey,a.key,a.value);else this.r(a.primaryKey,a.key,a.value)}else this.N=this.W=
p,this.ka=r,L(this.oa,b+" completed."),this.r(k,k,k)};u.N=p;u.W=p;u.ka=r;
u.u=function(a,b,c){var d="IDBCursor: "+this.Q+":"+this.F;this.N=a;this.W=b;this.ka=!!c;a=this.s;if(b!=p)if(this.s!=p){if(1==W.cmp(b,this.s.lower)){L(this.oa,d+" not opened, index key out of range "+b+">="+this.s.lower);this.q(k,k,k);return}a=Ub.bound(b,this.s.upper,r,this.s.upperOpen)}else a=Ub.lowerBound(b);b=this.wa?this.index?this.P!=p?this.index.openKeyCursor(a,this.P):a!=p?this.index.openKeyCursor(a):this.index.openKeyCursor():this.P!=p?this.Y.openCursor(a,this.P):a!=p?this.Y.openCursor(a):
this.Y.openCursor():this.index?this.P!=p?this.index.openCursor(a,this.P):a!=p?this.index.openCursor(a):this.index.openCursor():this.P!=p?this.Y.openCursor(a,this.P):a!=p?this.Y.openCursor(a):this.Y.openCursor();L(this.oa,d+" opened, request "+b.readyState);b.onsuccess=pa(this.hc,this);b.onerror=pa(this.G,this)};u.advance=function(a){this.j?this.j.advance(a):j(new ic("IDBCursor:"+this.Q+":"+this.F+" cursor gone."))};
u.forward=function(a){var b="IDBCursor:"+this.Q+":"+this.F;if(a===r)L(this.oa,b+" restarting."),this.u();else if(this.j)if(a===n)this.j["continue"]();else if(a!=p)this.j["continue"](a);else this.r(k,k,k),L(this.oa,b+" resting.");else j(new ic(b+" cursor gone."))};u.ta=function(){return!!this.j};u.xb=function(){return this.j.key};u.K=function(){return this.j.primaryKey};u.hb=function(){return this.j.value};
u.seek=function(a,b,c){var d="IDBCursor:"+this.Q+":"+this.F;this.W=b;this.N=a;this.ka=!!c;if(this.j){var e=W.cmp(a,this.j.primaryKey),f=0==e||1==e&&!this.na||-1==e&&this.na;if(b!=p)if(c=W.cmp(this.j.key,b),e=1==c&&!this.na||-1==c&&this.na,0===c)if(f)this.j["continue"]();else this.u(a,b);else if(e)this.j["continue"](b);else L(this.oa,d+" restarting for "+a),this.u(a,b);else if(0===e)this.j["continue"]();else if(f)this.j["continue"]();else this.u(a,b,c)}else j(new pc(d+" cursor gone."))};
u.xc=function(a){if(this.j){var b=new G;a=this.j.update(a);a.onsuccess=function(a){H(b,a)};a.onerror=function(a){I(b,a)};return b}j(new rc("cursor gone"))};function Wd(a,b){wc.call(this,a,b)}D(Wd,xc);u=Wd.prototype;u.n=M("ydn.db.index.req.IndexedDb");u.Eb=function(a,b){var c=mc(b,this);c.G=function(b){I(a,b)};c.q=function(c,e,f){lc(b);H(a,b.w?e:f)}};u.i=s("e");u.Hb=function(a,b,c,d){var e=[],f=mc(b,this);f.G=function(b){I(a,b)};var g=0,h=r;f.q=function(m,l){w(l)?!h&&0<d?(f.advance(d),h=n):(g++,e.push(l),!w(c)||g<c?f.forward(n):(lc(b),H(a,e))):H(a,e)}};
u.xa=function(a,b,c,d){var e=[],f=mc(b,this);f.G=function(b){I(a,b)};var g=0,h=r;f.q=function(m,l,q){w(l)?!h&&0<d?(f.advance(d),h=n):(g++,e.push(b.w?m:q),!w(c)||g<c?f.forward(n):(lc(b),H(a,e))):H(a,e)}};u.Pa=function(a,b,c,d,e){var f=this.i().objectStore(a);return new Vd(f,a,b,c,d,e)};function Xd(a,b,c,d,e,f,g,h,m){yd.call(this,c,d,e,f,g);this.e=a;this.Ha=b;this.fa=this.S=this.ea=p;this.u(h,m)}D(Xd,yd);u=Xd.prototype;u.Ga=M("ydn.db.index.req.WebsqlCursor");u.Ha=p;u.z=p;u.C=p;u.T=p;u.S=p;u.ea=p;u.fa=p;
u.u=function(a,b){var c=this.Q+":"+this.F;this.ea=[];this.S=[];this.fa=[];var d=this.s;if(b!=p)if(this.s!=p){var e=W.cmp(b,this.s.upper);if(1==e||0==e&&!this.s.upperOpen){this.q(k,k,k);return}d=Ub.bound(b,this.s.upper,r,this.s.upperOpen)}else d=Ub.lowerBound(b);var f=this,g=["SELECT"],e=[],h=this.F?this.F:"_ROWID_",m=E(h),l=id(this.Ha),q=E(l);g.push(this.wa?m+", "+q:"*");g.push("FROM "+E(this.Q));d=Wb(h,d);d.sql&&(g.push("WHERE "+d.sql),e=e.concat(d.ob));a!=p&&(d.sql?g.push("AND _ROWID_ = ?"):g.push("WHERE _ROWID_ = ?"),
e.push(a));g.push(" ORDER BY "+m+" "+(this.na?"DESC":"ASC"));this.wa?g.push(" LIMIT 100"):g.push(" LIMIT 1");this.jb=n;g=g.join(" ");L(f.Ga,"Iterator: "+c+" opened: "+g);this.e.executeSql(g,e,function(a,b){f.jb=r;for(var d=b.rows.length,e=0;e<d;e++){var g=b.rows.item(e);f.ea[e]=gd(g[l],f.Ha.type);f.wa?f.S[e]=gd(g[h],f.Ha.type):g!=p&&(f.fa[e]=fd(g,f.Ha))}0<d?(f.C=f.ea.shift(),f.z=f.S.shift(),f.T=f.fa.shift(),f.r(f.C,f.z,f.T)):(L(f.Ga,"Iterator: "+c+" completed."),f.r(k,k,k))},function(a,b){J(f.Ga,
"get error: "+b.message);f.G(b);return n})};
u.forward=function(a){var b=this.Q+":"+this.F;if(a===r)L(this.Ga,"Iterator: "+b+" restarting."),this.u();else if(this.ta())if(a!=p)if(x(this.S)&&0<this.S.length)if(a===n)this.C=this.ea.shift(),this.z=this.S.shift(),this.T=this.fa.shift(),this.r(this.C,this.z,this.T);else{do{this.C=this.ea.shift();this.z=this.S.shift();this.T=this.fa.shift();if(!w(this.z)){this.u(p,a);return}if(0==nc(this.z,a)){this.r(this.C,this.z,this.T);return}}while(this.C!=p);this.u(p,a)}else a===n?this.u(this.C,this.z,n):this.u(p,
a);else this.r(k,k,k),this.T=this.C=this.z=p,L(this.Ga,"Cursor: "+b+" resting.");else j(new ic("Iterator:"+b+" cursor gone."))};u.ta=function(){return this.z!=p};u.xb=s("z");u.K=s("C");u.hb=s("T");u.seek=function(){j(new ec)};function Yd(a,b){wc.call(this,a,b)}D(Yd,ed);u=Yd.prototype;u.n=M("ydn.db.index.req.WebSql");u.Eb=function(a,b){var c=new G;Zd(this,c,b,r,1);c.R(function(b){x(b)?H(a,b[0]):H(a)},function(b){I(a,b)})};u.Hb=function(a,b,c,d){Zd(this,a,b,n,c,d)};u.xa=function(a,b,c,d){Zd(this,a,b,r,c,d)};
function Zd(a,b,c,d,e,f){var g=U(a.a,c.B),h=c.index,m=w(h)?Ld(g,h):p,h=E(m?m.keyPath:g.keyPath!=p?g.keyPath:"_ROWID_"),l="*";d?l=h:c.w&&(l=g.keyPath!=p?nd(g):"_ROWID_");var q=l+" FROM "+jd(g),t=c.c,A="",l=[];t&&(Xb(t)?(A=h+" LIKE ?",l.push(t.lower+"%")):(w(t.lower)&&(A+=" "+h+(t.lowerOpen?" > ":" >= ")+"?",l.push(t.lower)),w(t.upper)&&(A+=(0<A.length?" AND ":" ")+h+(t.upperOpen?" < ":" <= ")+"?",l.push(t.upper))),A=" WHERE ("+A+")");t="ASC";c.Sb()&&(t="DESC");var F="";w(e)&&(F=" LIMIT "+e);w(f)&&
(F+=" OFFSET "+f);e=["SELECT",q,A,"","ORDER BY "+h,t,F].join(" ");var Q;Q=d||c.w?function(a){return gd(Qb(a),m?m.type:g.type)}:function(a){return fd(a,g)};a.e.executeSql(e,l,function(a,c){for(var d=[],e=c.rows.length,f=0;f<e;f++){var g=c.rows.item(f);d.push(Q(g))}H(b,d)},function(c,d){J(a.n,"Sqlite error: "+d.message);I(b,d);return n})}u.Pa=function(a,b,c,d,e,f,g){var h=U(this.a,a);return new Xd(this.i(),h,a,b,c,d,e,f,g)};function $d(a,b){wc.call(this,a,b)}D($d,Zc);function ae(a,b,c,d){od.call(this,a);this.a=d}D(ae,V);u=ae.prototype;u.ha=function(){if(!this.l){var a=this.type();"indexeddb"==a?this.l=new Wd(this.J(),this.a):"websql"==a?this.l=new Yd(this.d,this.a):"memory"==a||"localstorage"==a||"sessionstorage"==a?this.l=new $d(this.d,this.a):j(new pc("No executor for "+a))}return this.l};u.f=function(a,b,c,d){ae.M.f.call(this,a,b,c,d)};
u.ca=function(a,b){if(a instanceof S){var c=new G,d=a.B,e=U(this.a,d);e||j(new P('store "'+d+'" not found.'));var f=a.index;w(f)&&!Md(e,f)&&j(new P('index "'+f+'" not found in store "'+d+'".'));this.f(function(b){b.Eb(c,a)},[d],R,"getByIterator");return c}return ae.M.ca.call(this,a,b)};
u.keys=function(a,b,c,d,e,f,g){if(a instanceof S){var h=new G;(w(c)||w(d)||w(e))&&j(new P("too many arguments."));var m;z(b)?(m=b,1>m&&j(new P("limit must be a positive value"))):w(b)&&j(new P("limit"));var l;z(c)?l=c:w(c)&&j(new P("offset"));this.f(function(b){b.Hb(h,a,m,l)},a.stores(),R,"listByIterator");return h}return ae.M.keys.call(this,a,b,c,d,e,f,g)};
u.ma=function(a,b,c,d,e,f,g){if(a instanceof S){var h=new G;(w(d)||w(e))&&j(new P("too many arguments."));var m;z(b)?(m=b,1>m&&j(new P("limit must be a positive value"))):w(b)&&j(new P("limit"));var l;z(c)?l=c:w(c)&&j(new P("offset"));this.f(function(b){b.xa(h,a,m,l)},a.stores(),R,"listByIterator");return h}return ae.M.ma.call(this,a,b,c,d,e,f,g)};
u.Xb=function(a,b,c){var d=new G;(!x(a)||!(a[0]instanceof S))&&j(new P);for(var e=[],f=0;f<a.length;f++)for(var g=a[f].stores(),h=0;h<g.length;h++)0<=ab(e,g[h])||e.push(g[h]);for(var m=c||[],f=0;f<m.length;f++)c=m[f].b,0<=ab(e,c)||e.push(c);this.f(function(c){function e(){for(var b=0,d=0;d<a.length;d++){var m=a[d],q=mc(m,c);q.G=f;q.q=qa(g,b);cc[d]=q;ea[b]=d;b++;for(var q=0,Q=m.Ua.length+1-1;q<Q;q++){var N=new vd(c.i(),m.Ua[q],m.$b[q],m.gc[q]),la=qa(h,b);N.tb=la;mb.push(N);ya[b]=mb.length;b++}}da=
a.length+mb.length}function f(a){fb(cc);fb(mb);I(d,a)}function g(b,c,d,e){N&&j(new fc);nb++;var f=a[ea[b]];la[b]=c;Ia[b]=f.w?d:e;b=ya[b];c=0;for(f=f.Ua.length+1-1;c<f;c++){var h=mb[b+c],m=d,l=e;w(h.d)?h.Xa?h.push(l):l!=p?h.push(l[h.d]):h.push(k,k):h.push(m)}nb===da&&Q()}function h(a,b,c){N&&j(new fc);la[a]=b;Ia[a]=c;nb++;nb===da&&Q();return r}function Q(){nb=0;var c;c=b instanceof Td?b.Va(la,Ia):b(la,Ia);var e=[],f=[],g=[];if(x(c))e=c;else if(c===p)e=[];else if(w(c))B(c)?(x(c.next_primary_keys)&&
(e=c.next_primary_keys),x(c.next_index_keys)&&(f=c.next_index_keys),x(c.advance)&&(g=c.advance)):j(new hc("scan callback output"));else{e=[];for(c=0;c<a.length;c++)w(ea[c])&&(e[c]=n)}var h=0;for(c=0;c<a.length;c++)if(e[c]!=p){w(ea[c])||j(new hc(c+" is not an iterator."));var m=cc[c];e[c]!==r&&!w(la[c])&&j(new ic("Iterator "+c+" must not advance."));la[c]=k;Ia[c]=k;w(e[c])&&w(f[c])?m.forward(e[c],f[c],!!g[c]):w(e[c])?ha(e[c])?m.forward(e[c]):m.seek(e[c]):w(f[c])?m.forward(f[c]):w(g[c])&&m.forward(!!g[c]);
h++}else nb++;if(0==h){for(e=0;e<a.length;e++)lc(a[e]);N=n;fb(cc);fb(mb);H(d)}}for(var N=r,da,ya=[],ea=[],la=[],Ia=[],cc=[],mb=[],nb=0,$c=0;$c<m.length;$c++)wd(m[$c],this.i());b instanceof Td?b.Ka(a,function(){e()})||e():e()},e,R,"join");return d};u.Wb=function(a,b,c){a instanceof S||j(new P);U(this.a,a.B)||j(new P('Store "'+a.B+'" not found.'));c=c||R;var d=new G;this.f(function(c){var f=mc(a,c);f.G=function(a){I(d,a)};f.q=function(a){a!=p?(b(f),f.forward(n)):H(d)}},a.stores(),c,"open");return d};
u.map=function(a,b){for(var c=a.stores(),d,e=0;d=c[e];e++)d||j(new P('Store "'+d+'" not found.'));var f=new G;this.f(function(c){var d=mc(a,c);d.G=function(a){I(f,a)};d.q=function(c,e,g){w(e)?(c=b(a.w?y(a.index)?e:c:y(a.index)?c:g),w(c)?(ha(c)&&j(new hc(c)),c===p?d.forward(p):d.forward(c)):d.forward(n)):H(f,k)}},c,R,"map");return f};
u.reduce=function(a,b,c){for(var d=a.stores(),e,f=0;e=d[f];f++)e||j(new P('Store "'+e+'" not found.'));var g=new G,h=B(c)?Ob(JSON.stringify(c)):c;this.f(function(c){var d=mc(a,c);d.G=function(a){I(g,a)};var e=0;d.q=function(c,f,m){c!=p?(h=b(h,a.w?y(a.index)?f:c:y(a.index)?c:m,e++),d.forward(n)):H(g,h)}},d,R,"map");return g};function be(a){this.a=a}be.prototype.a=[];
be.prototype.b=function(a,b){for(var c=[],d=0;d<this.a.length;d++){var e=this.a[d],f="'"===e[0]&&"'"===e[e.length-1];if('"'===e[0]&&'"'===e[e.length-1])e=tb(a,za(e,'"').split(".")),c.push(e);else if(f)c.push(za(e,"'"));else if(y(e))if("true"===e)c.push(n);else if("false"===e)c.push(r);else if("Date"===e)c.push(new Date(parseInt(c.pop(),10)));else if("now"===e)c.push(new Date);else if("!"===e)c[c.length-1]=!c[c.length-1];else if("=="===e)c.push(c.pop()==c.pop());else if("==="===e)c.push(c.pop()===
c.pop());else if("!="===e)c.push(c.pop()!=c.pop());else if("!=="===e)c.push(c.pop()!==c.pop());else if("<="===e)c.push(c.pop()<=c.pop());else if("<"===e)c.push(c.pop()<c.pop());else if(">="===e)c.push(c.pop()>=c.pop());else if(">"===e)c.push(c.pop()>c.pop());else if("&"===e)c.push(c.pop()&c.pop());else if("|"===e)c.push(c.pop()|c.pop());else if("?"===e){var e=!!c.pop(),f=c.pop(),g=c.pop(),e=e?f:g;c.push(e)}else"+"===e?c.push(c.pop()+c.pop()):"-"===e?c.push(c.pop()-c.pop()):"*"===e?c.push(c.pop()*
c.pop()):"/"===e?c.push(c.pop()/c.pop()):"%"===e?c.push(c.pop()%c.pop()):"at"===e?(f=c.pop(),e=c.pop(),c.push(e[f])):"of"===e?(f=c.pop(),e=c.pop(),e=x(e)?e.indexOf(f):-1,c.push(e)):"in"===e?(f=c.pop(),e=c.pop(),e=x(e)?0<=e.indexOf(f):r,c.push(e)):"abs"===e?c[c.length-1]=Math.abs(c[c.length-1]):"$"==e[0]&&/^\$\d$/.test(e)?(e=parseInt(e.match(/^\$(\d)$/)[1],10),c.push(arguments[e])):c.push(parseFloat(e));else c.push(e)}return c[0]};
be.prototype.c=function(){return function(){var a=2<arguments.length?Array.prototype.slice(arguments,2):k;return be.prototype.b.apply(p,a)}};be.prototype.toJSON=function(){return{Tokens:Ob(JSON.stringify(this.a))}};function ce(a){y(a)||j(new P);this.H=a;de(this,a);this.Da=""}u=ce.prototype;u.H="";u.Aa=R;u.Kb=NaN;u.Mb=NaN;u.rb=r;u.Da="";
function de(a,b){var c=b.split(/\sFROM\s/i);2!=c.length&&j(new uc("FROM required."));var d=c[1],c=c[0].match(/\s*?(SELECT|INSERT|UPDATE|DELETE)\s+(.*)/i);3!=c.length&&j(new uc("Unable to parse: "+b));a.c=c[1].toUpperCase();"SELECT"==a.c?a.Aa=R:"INSERT"==a.c?a.Aa=$b:"UPDATE"==a.c?a.Aa=$b:"DELETE"==a.c?a.Aa=$b:j(new uc("Unknown SQL verb: "+a.c));var c=c[2].trim(),e=c.match(/^(MIN|MAX|COUNT|AVG|SUM)/i);e?(a.d=e[0].toUpperCase(),c=c.replace(/^(MIN|MAX|COUNT|AVG|SUM)/i,"").trim()):a.d=k;"("==c.charAt(0)&&
(")"==c.charAt(c.length-1)?c=c.substring(1,c.length-1):new uc("missing closing parentheses"));a.D=c;c=d.search(/(ORDER BY|LIMIT|OFFSET)/i);0<c?(a.a=d.substring(c),d=d.substring(0,c)):a.a="";c=d.search(/WHERE/i);0<c?(a.h=d.substring(c+6).trim(),d=d.substring(0,c)):a.h="";a.b=d.trim().split(",").map(function(a){a=za(a,'"');a=za(a,"'");return a.trim()})}
u.parse=function(a){if(a){for(var b=0;b<a.length;b++)this.H=this.H.replace("?",a[b]);de(this,this.H)}this.m=ee(this);if(!this.m)return this.Da;a=this.a.length;if(b=/OFFSET\s+(\d+)/i.exec(this.a))this.Mb=parseInt(b[1],10),a=this.a.search(/OFFSET/i);if(b=/LIMIT\s+(\d+)/i.exec(this.a))this.Kb=parseInt(b[1],10),b=this.a.search(/LIMIT/i),b<a&&(a=b);(a=/ORDER BY\s+(.+)/i.exec(this.a.substr(0,a)))?(a=a[1].trim(),(b=a.match(/(ASC|DESC)/i))?(this.rb="DESC"==b[0].toUpperCase(),a=a.replace(/\s+(ASC|DESC)/i,
"")):this.rb=r,this.U=za(za(a,'"'),"'")):this.U=k;return""};function fe(a){if("*"==a.D)return p;a=a.D.split(",");return a=a.map(function(a){return a.trim()})}u.toJSON=function(){return{sql:this.H}};
function ee(a){function b(a){return eb(c,function(b){return b.X==a})}var c=[],d=/(.+?)(<=|>=|=|>|<)(.+)/i;if(0<a.h.length)for(var e=a.h.split("AND"),f=0;f<e.length;f++){var g=e[f],h=d.exec(g);if(h){var m=h[1].trim(),m=za(m,'"'),m=za(m,"'");if(0<m.length){var l=h[3].trim(),l=0==l.lastIndexOf('"',0)?za(l,'"'):0==l.lastIndexOf("'",0)?za(l,"'"):parseFloat(l),h=new Vb(m,h[2],l),m=b(m);if(0<=m){var l=c,q=m;var t=c[m];if(t.X!=h.X)h=p;else{var A=k,F=k,Q=k,N=k;t.lower!=p&&h.lower!=p?t.lower>h.lower?(A=t.lower,
Q=t.lowerOpen):t.lower==h.lower?(A=t.lower,Q=t.lowerOpen||h.lowerOpen):(A=h.lower,Q=h.lowerOpen):t.lower!=p?(A=t.lower,Q=t.lowerOpen):h.lower!=p&&(A=h.lower,Q=h.lowerOpen);t.upper!=p&&h.upper!=p?t.lower>h.upper?(F=t.upper,N=t.upperOpen):t.lower==h.lower?(F=t.upper,N=t.upperOpen||h.upperOpen):(F=h.upper,N=h.upperOpen):t.upper!=p?(F=t.upper,N=t.upperOpen):h.upper!=p&&(F=h.upper,N=h.upperOpen);h=new Vb(t.X,{lower:A,upper:F,lowerOpen:Q,upperOpen:N})}l[q]=h;if(!c[m])return a.Da='where clause "'+g+'" conflict',
p}else c.push(h)}else return a.Da='Invalid clause "'+g+'"',p}else return a.Da='Invalid clause "'+g+'"',p}return c}u.toString=function(){return ce.M.toString.call(this)};function ge(a,b){this.sql=b;this.a=a}ge.prototype.toJSON=function(){return{sql:this.sql}};ge.prototype.toString=ba("idb.Node:");
ge.prototype.Yb=function(a,b){var c=hb(this.sql.b)[0],d=this.sql.m,e=this.sql.Kb,e=isNaN(e)?1E6:e,f=this.sql.Mb,f=isNaN(f)?0:f,g=this.sql.U,h=fe(this.sql),m=p,l=this.sql.rb;0==d.length?m=p:1==d.length?m=Tb(d[0]):j(new dc("too many conditions."));h===p||0==h.length?g!=p&&g!=this.a.keyPath?(c=new kc(c,g,m,l),b.xa(a,c,e,f)):m?b.Sa(a,c,d[0].X,m,l,e,f,r):b.ya(a,c,m,l,e,f):1==h.length?g!=p&&g!=h[0]?(d=new G,c=new kc(c,g,m,l),b.xa(d,c,e,f),d.R(function(b){b=b.map(function(a){return tb(a,h[0])});H(a,b)},
function(b){I(a,b)})):(c=new jc(c,h[0],m,l),b.xa(a,c,e,f)):(d=new G,b.ya(d,c,m,l,e,f),d.R(function(a){a.map(function(a){for(var b={},c=0;c<h.length;c++)b[h[c]]=tb(a,h[c]);return b})},function(b){I(a,b)}))};function he(a,b){ge.call(this,a,b)}D(he,ge);
he.prototype.Yb=function(a,b){var c,d=hb(this.sql.b)[0],e=this.sql.m,f=p;0==e.length?f=p:1==e.length?f=Tb(e[0]):j(new dc("too many conditions."));var g=this.sql.d;if("COUNT"==g)f?b.qa(a,d,f,e[0].X):b.qa(a,d,p);else{var h,m=fe(this.sql);(!m||0==m.length)&&j(new ic("field name require for reduce operation: "+g));var l=m[0];"MIN"==g?h=function(a,b){var c=a[l];return!w(b)?c:b<c?b:c}:"MAX"==g?h=function(a,b){var c=a[l];return!w(b)?c:b>c?b:c}:"AVG"==g?(c=0,h=function(a,b,c){w(b)||(b=0);return(b*c+a[l])/
(c+1)}):"SUM"==g?(c=0,h=function(a,b){return b+a[l]}):j(new dc(g));var q=mc(f?new kc(d,e[0].X,f):new kc(d),b);q.G=function(b){I(a,b)};var t=0;q.q=function(b,d,e){w(d)?(c=h(e,c,t),q.advance(1),t++):H(a,c)}}};function ie(a,b){wc.call(this,a,b)}D(ie,Wd);ie.prototype.n=M("ydn.db.sql.req.IndexedDb");ie.prototype.executeSql=function(a,b,c){(c=b.parse(c))&&j(new uc(c));c=hb(b.b);if(1==c.length){var d=U(this.a,c[0]);d||j(new T(c[0]));var e=fe(b);if(e)for(var f=0;f<e.length;f++)Md(d,e[f])||j(new T('Index "'+e[f]+'" not found in '+c[0]));(b.d?new he(d,b):new ge(d,b)).Yb(a,this)}else j(new dc(b.H))};function je(a,b){this.sql=b;this.c=a;this.a=fe(b)}je.prototype.b=M("ydn.db.sql.req.websql.Node");je.prototype.toJSON=function(){return{sql:this.sql.H}};je.prototype.toString=ba("websql.Node:");function ke(a,b){if(a.a){if(1==a.a.length){if(B(b))return tb(b,a.a[0]);return}for(var c={},d=0;d<a.a.length;d++)c[a.a[d]]=tb(b,a.a[d]);return c}return fd(b,a.c)}
je.prototype.Zb=function(a,b,c){var d=this,e=[];b.executeSql(this.sql.H,c,function(b,c){for(var h=c.rows.length,m=0;m<h;m++){var l=c.rows.item(m);if(B(l))var q=ke(d,l);e.push(q)}H(a,e)},function(b,c){J(d.b,"Sqlite error: "+c.message);I(a,c);return n})};function le(a,b){je.call(this,a,b)}D(le,je);le.prototype.Zb=function(a,b,c){var d=this;b.executeSql(this.sql.H,c,function(b,c){var d=c.rows.length;1==d?(d=Qb(c.rows.item(0)),H(a,d)):0==d?H(a,k):j(new pc)},function(b,c){J(d.b,"Sqlite error: "+c.message);I(a,c);return n})};function me(a,b){wc.call(this,a,b)}D(me,Yd);me.prototype.n=M("ydn.db.sql.req.WebSql");me.prototype.executeSql=function(a,b,c){var d=hb(b.b);if(1==d.length){var e=U(this.a,d[0]);e||j(new T(d[0]));var f=fe(b);if(f)for(var g=0;g<f.length;g++)Md(e,f[g])||j(new T('Index "'+f[g]+'" not found in '+d[0]));(b.d?new le(e,b):new je(e,b)).Zb(a,this.e,c)}else j(new dc(b.H))};function ne(a,b){wc.call(this,a,b)}D(ne,$d);function oe(a,b,c,d){od.call(this,a);this.a=d}D(oe,ae);oe.prototype.ha=function(){if(!this.l){var a=this.type();"indexeddb"==a?this.l=new ie(this.J(),this.a):"websql"==a?this.l=new me(this.d,this.a):"memory"==a||"localstorage"==a||"sessionstorage"==a?this.l=new ne(this.d,this.a):j(new pc("No executor for "+a))}return this.l};oe.prototype.f=function(a,b,c,d){oe.M.f.call(this,a,b,c,d)};
oe.prototype.executeSql=function(a,b){for(var c=new G,d=new ce(a),e=hb(d.b),f=0;f<e.length;f++){var g=U(this.a,e[f]);g||j(new P("store: "+g+" not exists."))}this.f(function(a){a.executeSql(c,d,b||[])},hb(d.b),d.Aa,"executeSql");return c};function pe(){this.clear()}u=pe.prototype;u.setItem=function(a,b){w(this.a[a])||(this.keys.push(a.toString()),this.length=this.keys.length);this.a[a]=b};u.getItem=function(a){return this.a[a]||p};u.removeItem=function(a){delete this.a[a];gb(this.keys,a.toString());this.length=this.keys.length};u.length=0;u.key=function(a){a=this.keys[a];return w(a)?this.a[a]:p};u.clear=function(){this.a={};this.keys=[];this.length=0};function qe(a){this.o=a||new pe}u=qe.prototype;u.Vb=M("ydn.db.con.SimpleStorage");u.la=function(a,b){this.ga=a;this.c=b;this.a={};for(var c=0;c<b.stores.length;c++){var d=b.c(c);this.a[d.name]=d.toJSON()}this.indexes={};d=re(this);c=Ob(this.o.getItem(d));yc(b);if(c)for(var e in c)c.hasOwnProperty(e)&&!qd(b,e)&&(d=c[e],b.a()?(K(this.Vb,"Adding existing store: "+e),this.a[e]=d):(K(this.Vb,"Deleting old store: "+e),cd(this,e)));else this.o.setItem(d,JSON.stringify(this.a));return sb(n)};u.ub=function(){return!!this.ga};
u.type=ba("memory");u.Ya=aa();u.Ma=function(a,b,c,d){a(this);d("complete",{})};u.O=function(a){Yc(function(){for(var b=[],c=this.o.getItem(re(this)).stores,d=0;d<c.length;d++){var e=this.o.getItem(re(this,c[d]));b[d]=new Kd(c[d],e.keyPath,e.autoIncrement)}b=new Nd(this.ga,b);a(b)},0,this)};function re(a,b,c){a=["ydn.db",a.ga];w(b)&&(a.push(b),w(c)&&a.push(Ad(c)));return a.join("^|")}function bd(a,b,c){b=re(a,b instanceof Kd?b.name:b,c);a=a.o.getItem(b);return a=a===p?k:Ob(a)}
function ad(a,b,c,d){var e;e=U(a.c,c);d=w(d)?d:e.keyPath!=p?tb(b,e.a):k;w(d)||(e.autoIncrement?(re(a,e.name),d=a.a[e.name],w(d.autoIncrementNo)||(d.autoIncrementNo=dd(a,e.name,p).length),d.autoIncrementNo++,d=d.autoIncrementNo):j(new oc));e=d;d=re(a,c,e);b=JSON.stringify(b);a.o.setItem(d,b);if(a=a.a[c].Keys){c=0;for(b=a.length;c<b&&e!=a[c];c++)if(e>a[c]){ib(a,c,0,e);break}}return e}
function cd(a,b,c){if(w(c))a.o.removeItem(re(a,b,c)),a=a.a[b].Keys,w(a)&&gb(a,c);else if(w(b)){a.a[b]&&(a.a[b].Keys=p);c=re(a,b)+"^|";for(b=a.o.length-1;0<=b;b--){var d=a.o.key(b);0==d.lastIndexOf(c,0)&&a.o.removeItem(d)}}else{c=re(a)+"^|";for(b=a.o.length-1;0<=b;b--)d=a.o.key(b),0==d.lastIndexOf(c,0)&&a.o.removeItem(d)}}
u.index=function(a){var b=this.a[a],c=b.Keys;if(c==p){c=[];a=re(this,a);a+="^|";for(var d=0,e=this.o.length;d<e;d++){var f=this.o.key(d);if(0==f.lastIndexOf(a,0)){c.push(f);for(var f=0,g=b.indexes.length;f<g;f++);}}$a.sort.call(c,kb);b.Keys=c;b.indexes={}}return c};
function dd(a,b,c){function d(){return function(a){return a>=k}}function e(){return function(a){return a<k}}c!=p&&j(new ec);a=a.index(b);if(!w(k)&&!w(k))return a;if(w(k)){if(w(k))return b=eb(a,e()),c=eb(a,d()),a.slice(b,c);b=eb(a,d());return a.slice(b)}b=eb(a,e());return a.slice(0,b)};function se(){qe.call(this,window.localStorage)}D(se,qe);se.prototype.type=ba("localstorage");function te(){qe.call(this,window.sessionStorage)}D(te,qe);te.prototype.type=ba("sessionstorage");function ue(a,b){Ec.call(this,a,b)}D(ue,Ec);function ve(a,b,c,d){Ec.call(this,a,b);this.message=d||""}D(ve,ue);ve.prototype.message="";function we(a,b){Nd.call(this,a,b)}D(we,Nd);we.prototype.a=ba(n);/*
 Copyright 2012 YDN Authors, Yathit. All Rights Reserved.
*/
function X(a,b,c){Ac.call(this);c=c||{};this.Ra=c.mechanisms||xe;this.D=c.size;this.Qb=w(c.Qb)?c.Qb:n;this.b=p;this.m=[];this.Qa=r;this.a=b instanceof Nd?b:B(b)?c.autoSchema||!w(b.stores)?new we(b):new Nd(b):new we;w(a)&&this.Nb(a)}D(X,Wc);u=X.prototype;u.Za=M("ydn.db.con.Storage");u.tc=function(a){if(w(a)){var b=function(b){a(b.toJSON())};if(this.b)this.b.O(b);else{var c=this;this.ba(function(a){c.b.O(b,a)},p,R)}}return this.a?this.a.toJSON():p};
u.ab=function(a){var b=a instanceof Kd?a:rd(a);a=a.name;var c=U(this.a,a);if(0==sd(b,c).length)return sb(r);c=c?"update":"add";if(this.a instanceof we)return this.a.stores.push(b),this.b?(this.b.Ya(),this.b=p,ye(this)):sb(r);j(new gc("Cannot "+c+" store: "+a+". Not auto schema generation mode."))};u.Nb=function(a){this.b&&j(Error("Already defined."));this.d=a;ye(this)};u.J=s("d");var xe=["indexeddb","websql","localstorage","sessionstorage","memory"];
function ze(a,b){return"indexeddb"==b?new Pd(a.D):"websql"==b?new Rd(a.D):"localstorage"==b?new se:"sessionstorage"==b?new te:"memory"==b?new qe:p}
function ye(a){for(var b=new G,c=p,d=a.Ra,e=0;e<d.length;e++){var f=d[e].toLowerCase();if("indexeddb"==f&&W){c=ze(a,f);break}else if("websql"==f&&ia(v.openDatabase)){c=ze(a,f);break}else if("localstorage"==f&&window.localStorage){c=ze(a,f);break}else if("sessionstorage"==f&&window.sessionStorage){c=ze(a,f);break}else if("memory"==f){c=ze(a,f);break}}c===p&&j(new gc("No storage mechanism found."));c.la(a.d,a.a).Ia(function(){a.b=c;L(a.Za,a+": ready.");a.uc=NaN;sb(n);Ae(a);Vc(a,new ve("connected",a));
c.b=function(){L(a.Za,a+": disconnected.")}}).Ja(function(b){J(a.Za,a+": opening fail: "+b.message);I(new G,b);if(a.m){a.Za.log(Gb,"Purging "+a.m.length+" transactions request.",k);for(var c=a.m.shift();c;)c.L("error",b),c=a.m.shift()}Vc(a,new ve("failed",a,0,"opening database fail: "+b.message))});return b}u=X.prototype;u.type=function(){return this.b?this.b.type():""};u.vb=function(){this.b&&(this.b.Ya(),this.b=p)};u.uc=NaN;
function Ae(a){var b=a.m.shift();b&&X.prototype.ba.call(a,b.gb,b.jc,b.mode,b.L);ra()}u.Qa=r;u.ba=function(a,b,c,d){var e=b;y(b)?e=[b]:b!=p?(!x(b)||!y(b[0]))&&j(new P("storeNames")):e=p;if(!this.b||!this.b.ub()||this.Qa)this.m.push({gb:a,jc:e,mode:c,L:d}),ra();else{var f=this,g=w(c)?c:R;g==ac&&(this.Qa=n);this.b.Ma(function(b){a(b)},e,g,function(a,b){ia(d)&&d(a,b);g==ac&&(f.Qa=r);Ae(f)})}};u.toString=function(){return"ydn.db.con.Storage:"+this.b};function pd(){this.a=p}pd.prototype.c=M("ydn.db.tr.Mutex");pd.prototype.L=p;pd.prototype.i=s("a");pd.prototype.toString=ba("Mutex");function Be(a,b,c){X.call(this,a,b,c);this.h=0}D(Be,X);Be.prototype.h=0;Be.prototype.ia=function(){return new od(this,this.h++)};Be.prototype.$=function(a,b,c,d,e){var f=this.ia(a.name||"");if(4<arguments.length){var g=Array.prototype.slice.call(arguments,4),h=function(){var b=Array.prototype.slice.call(arguments),b=b.concat(g);return a.apply(this,b)};h.name=a.name;f.$(h,b,c,d)}else f.$(a,b,c,d)};function Y(a,b,c){Be.call(this,a,b,c);this.c=this.ia("base")}D(Y,Be);u=Y.prototype;u.ia=function(){return new V(this,this.h++,0,this.a)};u.$a=function(a,b,c){return this.c.$a(a,b,c)};u.ca=function(a,b){return this.c.ca(a,b)};u.keys=function(a,b,c,d,e,f,g){return this.c.keys(a,b,c,d,e,f,g)};u.ma=function(a,b,c,d,e,f,g){return this.c.ma(a,b,c,d,e,f,g)};u.Fa=function(a,b,c){return this.c.Fa(a,b,c)};u.clear=function(a,b){return this.c.clear(a,b)};u.toString=function(){return"Storage:"+this.J()};function Ce(a,b,c){Y.call(this,a,b,c)}D(Ce,Y);u=Ce.prototype;u.ia=function(){return new ae(this,this.h++,0,this.a)};u.vc=function(a,b,c){return this.c.Wb(a,b,c)};u.wc=function(a,b,c){return this.c.Xb(a,b,c)};u.map=function(a,b){return this.c.map(a,b)};u.reduce=function(a,b,c){return this.c.reduce(a,b,c)};function De(a,b,c){Y.call(this,a,b,c)}D(De,Ce);De.prototype.ia=function(){return new oe(this,this.h++,0,this.a)};De.prototype.executeSql=function(a,b){return this.c.executeSql(a,b)};function Z(a,b,c,d){od.call(this,a);this.a=d}D(Z,oe);var Ee={name:"default_text_store",keyPath:"id",type:"TEXT"};Z.prototype.h=function(a,b,c){var d=this.da().U||p;d&&(b=d.Bc(a,b,c));c="default_text_store";qd(this.a,"default_text_store")||(this.a.a()?c=Ee:j(new P("key-value store not in used.")));return this.Fa(c,{id:a,value:b})};
Z.prototype.getItem=function(a){var b=this.ca("default_text_store",a),c=new G,d=this;b.Ia(function(b){if(w(b)){b=b.value;var f=d.da().U||p;f&&w(b)&&(b=f.Ac(a,b));H(c,b)}else H(c,k)});b.Ja(function(a){I(c,a)});return c};Z.prototype.toString=function(){return"TxStorage:"+this.da().J()};function $(a,b,c){Y.call(this,a,b,c)}D($,De);$.prototype.ia=function(){return new Z(this,this.h++,0,this.a)};$.prototype.getItem=function(a){return this.c.getItem(a)};$.prototype.ua=function(a,b,c){return this.c.h(a,b,c)};$.prototype.toString=function(){return"Storage:"+this.J()};function Fe(a,b){Td.call(this,a,b)}D(Fe,Td);Fe.prototype.Ka=ba(r);Fe.prototype.Va=function(a){function b(e){w(a[e])?(d=r,c[e]=n):(c[e]=r,0<=e-1&&b(e-1))}var c=[],d=n;b(a.length-1);d&&(c=[]);return Ud(this,c,a)};function Ge(a,b){Td.call(this,a,b)}D(Ge,Td);Ge.prototype.Ka=ba(r);function He(a){var b=[],c=a[0];if(c==p)return{advance:[],Fb:p,yb:r,a:r};for(var d=n,e=r,f=c,g=[],h=1;h<a.length;h++)if(a[h]!=p){var m=nc(c,a[h]);g[h]=m;1===m?d=r:-1===m&&(d=r,e=n,1===nc(a[h],f)&&(f=a[h]))}else d=r,e=n;if(d)for(h=0;h<a.length;h++)a[h]!=p&&(b[h]=n);else if(e)for(h=0;h<a.length;h++)a[h]!=p&&1===nc(f,a[h])&&(b[h]=f);else for(h=1;h<a.length;h++)1===g[h]&&(b[h]=c);return{advance:b,Fb:f,yb:d,a:e}}
Ge.prototype.Va=function(a){var b=He(a);return Ud(this,b.advance,a)};function Ie(a,b){Td.call(this,a,b);this.aa=[];this.Ub=[];this.nb=r}D(Ie,Td);u=Ie.prototype;u.aa=[];u.Ub=[];u.nb=r;u.Ka=function(a){1==a.length&&j(new hc("number of iterators must be more than one."));2<a.length&&(this.nb=n);fb(this.aa);fb(this.Ub);return r};
u.Va=function(a){var b,c=r,d;this.nb?(d=He(a.slice(1)),b=d.advance,c=d.yb,d=d.Fb):a[1]!=p?(b=[n],d=a[1],c=n):b=[];if(0==b.length)return fb(this.aa),[];for(var e=this.aa.length-1;0<e;e--)-1!=nc(this.aa[e],d)&&this.aa.splice(e,1);c?b.unshift(n):(this.aa.push(a[0]),b.unshift(p));return b};C("ydn.db.KeyIterator",jc);C("ydn.db.ValueIterator",kc);S.prototype.continued=S.prototype.h;S.prototype.count=S.prototype.lc;S.prototype.done=S.prototype.cc;S.prototype.getKeyRange=S.prototype.ec;S.prototype.getIndexName=S.prototype.mc;S.prototype.getStoreName=S.prototype.nc;S.prototype.indexKey=S.prototype.oc;S.prototype.isReversed=S.prototype.Sb;S.prototype.isUnique=S.prototype.fc;S.prototype.isKeyOnly=S.prototype.pc;S.prototype.key=S.prototype.key;S.prototype.resume=S.prototype.ic;
S.prototype.reset=S.prototype.qc;C("ydn.db.Storage",$);$.prototype.scan=$.prototype.wc;$.prototype.map=$.prototype.map;$.prototype.reduce=$.prototype.reduce;$.prototype.open=$.prototype.vc;$.prototype.setItem=$.prototype.ua;$.prototype.getItem=$.prototype.getItem;Z.prototype.scan=Z.prototype.Xb;Z.prototype.map=Z.prototype.map;Z.prototype.reduce=Z.prototype.reduce;Z.prototype.open=Z.prototype.Wb;Z.prototype.setItem=Z.prototype.h;Z.prototype.getItem=Z.prototype.getItem;Vd.prototype.getPrimaryKey=Vd.prototype.K;
Vd.prototype.getIndexKey=Vd.prototype.xb;Vd.prototype.getValue=Vd.prototype.hb;Vd.prototype.update=Vd.prototype.xc;Vd.prototype.clear=Vd.prototype.clear;C("ydn.math.Expression",be);be.prototype.evaluate=be.prototype.b;be.prototype.compile=be.prototype.c;be.parseRpn=function(a){return new be(a.match(/[^\s"']+|"[^"]*"|'[^']*'/g))};be.parseInfix=function(){j(new ec("Too lazy to learn Dutch in Shunting Yard station, we speak Polish here."))};C("ydn.db.algo.NestedLoop",Fe);
C("ydn.db.algo.AbstractSolver",Td);C("ydn.db.algo.ZigzagMerge",Ie);C("ydn.db.algo.SortedMerge",Ge);G.prototype.done=G.prototype.Ia;G.prototype.fail=G.prototype.Ja;G.prototype.then=G.prototype.R;Wc.prototype.addEventListener=Wc.prototype.addEventListener;C("ydn.db.con.Storage",X);X.prototype.type=X.prototype.type;X.prototype.setName=X.prototype.Nb;X.prototype.getSchema=X.prototype.tc;X.prototype.transaction=X.prototype.ba;X.prototype.close=X.prototype.vb;
C("ydn.db.deleteDatabase",function(a){function b(){c.p.log(Gb,"all tables in "+a+" deleted.",k)}W&&"deleteDatabase"in W&&W.deleteDatabase(a);var c=new Rd,d=new we,d=c.la(a,d);d.Ia(function(){c.Ma(function(b){c.O(function(d){var e=d.stores.length;if(0<e)for(var m=0;m<e;m++){var l=d.c(m);K(c.p,"deleting table: "+l.name);b.executeSql("DROP TABLE "+jd(l))}else c.p.log(Gb,"no table to delete in "+a,k)},b)},[],$b,b)});d.Ja(function(){J(c.p,"Connecting "+a+" failed.")});var d=new se,e=new we;d.la(a,e);cd(d);
d=new te;e=new we;d.la(a,e);cd(d)});C("ydn.db.core.Storage",Y);Y.prototype.get=Y.prototype.ca;Y.prototype.list=Y.prototype.ma;Y.prototype.put=Y.prototype.Fa;Y.prototype.clear=Y.prototype.clear;Y.prototype.count=Y.prototype.$a;V.prototype.get=V.prototype.ca;V.prototype.list=V.prototype.ma;V.prototype.put=V.prototype.Fa;V.prototype.clear=V.prototype.clear;V.prototype.count=V.prototype.$a;C("ydn.db.cmp",nc);C("ydn.db.Key",vc);vc.prototype.id=vc.prototype.dc;vc.prototype.parent=vc.prototype.rc;vc.prototype.storeName=vc.prototype.sc;
C("ydn.db.KeyRange",O);O.upperBound=function(a,b){return new O(k,a,k,b)};O.lowerBound=function(a,b){return new O(a,k,b,k)};O.bound=Sb;O.only=function(a){return new O(a,a,r,r)};O.starts=function(a){var b;x(a)?(b=Ob(JSON.stringify(a)),b.push("\uffff")):y(a)?b=a+"\uffff":j(new P);return Sb(a,b,r,n)};C("ydn.db.tr.Storage",Be);Be.prototype.run=Be.prototype.$;od.prototype.run=od.prototype.$;})();
